compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.3.1.cjs

# CI optimizations
enableScripts: true
enableStrictSsl: false

# Sharp optimization for CI
enableHardenedMode: false
