version: '3.7'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.development
    ports:
      - '5000:5000'
    links:
      - mysql
      - minio
    env_file:
      - .env
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./server:/app/server
      - ./types:/app/types
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - '3306:3306'
      - '33060:33060'
    volumes:
      - ./.mysql-data:/var/lib/mysql

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    volumes:
      - ./.minio-data:/data
    command: server /data
