version: '3.7'
services:
  nginx:
    image: nginx:1.23.0
    ports:
      - 5000:80
    links:
      - backend
    volumes:
      - ./nginx-proxy-staging.conf:/etc/nginx/nginx.conf:ro

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.development
    env_file:
      - .env
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./server:/app/server
      - ./types:/app/types
    command: [ "yarn", "dev-staging" ]
