version: "3.7"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.development
    ports:
      - "5000:5000"
    links:
      - mysql
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./server:/app/server
      - ./types:/app/types

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./.mysql-data:/var/lib/mysql
