# services:
#   mysql:
#     image: mysql:8
#     environment:
#       - MYSQL_ROOT_PASSWORD=my-secret-pw
#     healthcheck:
#       test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
#       timeout: 20s
#       retries: 10
#     ports:
#       - '3306:3306'
#       - '33060:33060'
#     volumes:
#       - ./.mysql-data:/var/lib/mysql
#   minio:
#     image: minio/minio
#     ports:
#       - '9000:9000'
#       - '9090:9090'
#     environment:
#       - MINIO_ROOT_USER=minioadmin
#       - MINIO_ROOT_PASSWORD=minioadmin
#       - MINIO_ACCESS_KEY=minio
#       - MINIO_SECRET_KEY=minio123
#     volumes:
#       - ./.minio-data:/data
#     command: server --console-address ":9090" /data
