export const activitiesLabel = [
  'Présentation',
  'Enigme',
  'Défi',
  'Question',
  'Jeux',
  'Contenu libre',
  'Indice',
  'Symbole',
  'Mascotte',
  'Reportage',
  'Reaction',
  'Hymne',
  'Couplet ?',
  'Histoire',
  'Réinventer une histoire',
];
