import { TrackType } from '../../types/anthem.type';
import type { AnthemData } from '../../types/anthem.type';

export const DEFAULT_ANTHEM_DATA: AnthemData = {
  tracks: [
    {
      type: TrackType.INTRO_CHORUS,
      label: 'Piste intro + refrain chanté',
      sampleUrl: '',
      sampleDuration: 0,
      iconUrl: 'accordion',
      sampleStartTime: 0,
      sampleVolume: 1,
    },
    {
      type: TrackType.VOCALS,
      label: 'Piste vocale La La',
      sampleUrl: '',
      sampleDuration: 0,
      iconUrl: 'accordion',
      sampleStartTime: 0,
      sampleVolume: 1,
    },
    {
      type: TrackType.HARMONIC1,
      label: 'Piste harmonique 1',
      sampleUrl: '',
      sampleDuration: 0,
      iconUrl: 'slide_guitar',
      sampleStartTime: 0,
      sampleVolume: 1,
    },
    {
      type: TrackType.HARMONIC2,
      label: 'Piste harmonique 2',
      sampleUrl: '',
      sampleDuration: 0,
      iconUrl: 'electric_guitar',
      sampleStartTime: 0,
      sampleVolume: 1,
    },
    {
      type: TrackType.MELODIC1,
      label: 'Piste mélodique 1',
      sampleUrl: '',
      sampleDuration: 0,
      iconUrl: 'piano',
      sampleStartTime: 0,
      sampleVolume: 1,
    },
    {
      type: TrackType.MELODIC2,
      label: 'Piste mélodique 2',
      sampleUrl: '',
      sampleDuration: 0,
      iconUrl: 'electric_piano',
      sampleStartTime: 0,
      sampleVolume: 1,
    },
    {
      type: TrackType.RYTHMIC1,
      label: 'Piste rythmique 1',
      sampleUrl: '',
      sampleDuration: 0,
      iconUrl: 'maraca',
      sampleStartTime: 0,
      sampleVolume: 1,
    },
    {
      type: TrackType.RYTHMIC2,
      label: 'Piste rythmique 2',
      sampleUrl: '',
      sampleDuration: 0,
      iconUrl: 'jazz_set',
      sampleStartTime: 0,
      sampleVolume: 1,
    },
    {
      type: TrackType.OUTRO,
      label: 'Piste outro',
      sampleUrl: '',
      sampleDuration: 0,
      iconUrl: 'accordion',
      sampleStartTime: 0,
      sampleVolume: 1,
    },
  ],
  verseLyrics: [],
  chorusLyrics: [],
  mixUrl: '',
  fullMixUrl: '',
};
