import { TrackType } from '../../types/anthem.type';
import type { AnthemData } from '../../types/anthem.type';

export const DEFAULT_ANTHEM_DATA: AnthemData = {
  tracks: [
    {
      type: TrackType.INTRO_CHORUS,
      label: 'Piste intro + refrain chanté',
      sampleUrl: '',
      sampleDuration: 0,
      sampleStartTime: 0,
      sampleVolume: 0.5,
      iconUrl: '',
    },
    {
      type: TrackType.VOCALS,
      label: 'Piste vocale La La',
      sampleUrl: '',
      sampleDuration: 0,
      sampleStartTime: 0,
      sampleVolume: 0.5,
      iconUrl: '',
    },
    {
      type: TrackType.HARMONIC1,
      label: 'Piste harmonique 1',
      sampleUrl: '',
      sampleDuration: 0,
      sampleStartTime: 0,
      sampleVolume: 0.5,
      iconUrl: '',
    },
    {
      type: TrackType.HARMONIC2,
      label: 'Piste harmonique 2',
      sampleUrl: '',
      sampleDuration: 0,
      sampleStartTime: 0,
      sampleVolume: 0.5,
      iconUrl: '',
    },
    {
      type: TrackType.MELODIC1,
      label: 'Piste mélodique 1',
      sampleUrl: '',
      sampleDuration: 0,
      sampleStartTime: 0,
      sampleVolume: 0.5,
      iconUrl: '',
    },
    {
      type: TrackType.MELODIC2,
      label: 'Piste mélodique 2',
      sampleUrl: '',
      sampleDuration: 0,
      sampleStartTime: 0,
      sampleVolume: 0.5,
      iconUrl: '',
    },
    {
      type: TrackType.RYTHMIC1,
      label: 'Piste rythmique 1',
      sampleUrl: '',
      sampleDuration: 0,
      sampleStartTime: 0,
      sampleVolume: 0.5,
      iconUrl: '',
    },
    {
      type: TrackType.RYTHMIC2,
      label: 'Piste rythmique 2',
      sampleUrl: '',
      sampleDuration: 0,
      sampleStartTime: 0,
      sampleVolume: 0.5,
      iconUrl: '',
    },
    {
      type: TrackType.OUTRO,
      label: 'Piste outro',
      sampleUrl: '',
      sampleDuration: 0,
      sampleStartTime: 0,
      sampleVolume: 0.5,
      iconUrl: '',
    },
  ],
  verseLyrics: [],
  chorusLyrics: [],
  mixUrl: '',
  fullMixUrl: '',
};
