const userAdmin = {
  id: 1,
  email: 'admin.1village@parlemonde.org',
  pseudo: 'PLMO1_admin',
  firstname: 'Admin',
  lastname: '1Village',
  level: '',
  school: 'Asso Par Le Monde',
  city: 'Paris',
  postalCode: '75000',
  adress: '4 avenue Victoria',
  avatar: '',
  displayName: 'Admin 1Village',
  hasAcceptedNewsletter: false,
  language: 'français',
  accountRegistration: 0,
  passwordHash: 'helloWorld*',
  verificationHash: '',
  isVerified: true,
  firstLogin: 1,
  villageId: null,
  countryCode: 'FR',
  positionLat: '48.8588443',
  positionLon: '2.3469112',
  hasStudentLinked: false,
  type: 0,
};
