export type InstrumentsType = {
  name: string;
  value: string;
};

const instruments: InstrumentsType[] = [
  { name: 'Accordéon', value: 'accordion' },
  { name: 'Alboka', value: 'alboka' },
  { name: 'Clarinette Alto', value: 'alto_clarinet' },
  { name: 'Sarrusophone Alto', value: 'alto_sarrusophone' },
  { name: 'Dulcimer Appalachien', value: 'appalachian_dulcimer' },
  { name: 'Archiluth', value: 'archlute' },
  { name: 'Guitare Archtop', value: 'archtop_guitar' },
  { name: 'Arghoul', value: 'arghul' },
  { name: 'Aulochrome', value: 'aulochrome' },
  { name: 'Autoharpe', value: 'autoharp' },
  { name: 'Baglama', value: 'baglama' },
  { name: 'Cornemuse', value: 'bagpipe' },
  { name: 'Balalaïka', value: 'balalaika' },
  { name: 'Bandonéon', value: 'bandoneon' },
  { name: 'Bandoura', value: 'bandura' },
  { name: 'Banjo', value: 'banjo' },
  { name: 'Saxophone Baryton', value: 'bari_sax' },
  { name: 'Cor Baryton', value: 'baritone_horn' },
  { name: 'Baryton', value: 'barytone' },
  { name: 'Clarinette Basse', value: 'bass_clarinet' },
  { name: 'Tambour Basse', value: 'bass_drum' },
  { name: 'Guitare Basse', value: 'bass_guitar' },
  { name: 'Hautbois Basse', value: 'bass_oboe' },
  { name: 'Clarinette Basset', value: 'basset_clarinet' },
  { name: 'Cor de Basset', value: 'basset_horn' },
  { name: 'Basson', value: 'bassoon' },
  { name: 'Bawu', value: 'bawu' },
  { name: 'Bayan', value: 'bayan' },
  { name: 'Cloche', value: 'bell' },
  { name: 'Bifora', value: 'bifora' },
  { name: 'Biwa', value: 'biwa' },
  { name: 'Bodhran', value: 'bodhran' },
  { name: 'Bombarde', value: 'bombarde' },
  { name: 'Bongo', value: 'bongo' },
  { name: 'Boomwhackers', value: 'boomwhackers' },
  { name: 'Bouzouki', value: 'bouzouki' },
  { name: 'Clairon', value: 'bugle' },
  { name: 'Bullroarer', value: 'bullroarer' },
  { name: 'Accordéon à boutons', value: 'button_accordion' },
  { name: 'Castagnettes', value: 'castanets' },
  { name: 'Cavaquinho', value: 'cavaquinho' },
  { name: 'Célesta', value: 'celesta' },
  { name: 'Chapman Stick', value: 'chapman_stick' },
  { name: 'Carillon', value: 'chime' },
  { name: 'Trompette chinoise', value: 'chinese_trumpet' },
  { name: 'Accordéon chromatique', value: 'chromatic_accordion' },
  { name: 'Ciftelia', value: 'ciftelia' },
  { name: 'Guitare à boîte à cigares', value: 'cigar_box_guitar' },
  { name: 'Cymbalum', value: 'cimbalom' },
  { name: 'Cimbasso', value: 'cimbasso' },
  { name: 'Clarinette', value: 'clarinet' },
  { name: "Clarinette d'amour", value: 'clarinette_damour' },
  { name: 'Clavicorde électrique', value: 'clavecin_electrique' },
  { name: 'Clavicorde', value: 'clavichord' },
  { name: 'Piano à queue', value: 'concert_grand' },
  { name: 'Concertina', value: 'concertina' },
  { name: 'Coquille', value: 'conch' },
  { name: 'Conga', value: 'conga' },
  { name: 'Conn-O-Sax', value: 'conn_o_sax' },
  { name: 'Continuum', value: 'continuum' },
  { name: 'Hautbois contrabasse', value: 'contrabass_oboe' },
  { name: 'Contrebasson', value: 'contrabassoon' },
  { name: 'Cor anglais', value: 'cor_anglais' },
  { name: 'Cornet', value: 'cornet' },
  { name: 'Cornett', value: 'cornett' },
  { name: 'Cromorne', value: 'crumhorn' },
  { name: 'Crwth', value: 'crwth' },
  { name: 'Cuica', value: 'cuica' },
  { name: 'Cumbus', value: 'cumbus' },
  { name: 'Cymbales', value: 'cymbals' },
  { name: 'Dhol', value: 'dhol' },
  { name: 'Didgeridoo', value: 'didgeridoo' },
  { name: 'Diple', value: 'diple' },
  { name: 'Table de mixage DJ', value: 'dj_mixer' },
  { name: 'Platine DJ', value: 'dj_turntable' },
  { name: 'Dotara', value: 'dotara' },
  { name: 'Guitare à double manche', value: 'double_neck_guitar' },
  { name: 'Doyra', value: 'doyra' },
  { name: 'Dramyin', value: 'dramyin' },
  { name: 'Boîte à rythmes', value: 'drum_machine' },
  { name: 'Tambour', value: 'drum' },
  { name: 'Dulzaina', value: 'dulzaina' },
  { name: 'Ektara', value: 'ektara' },
  { name: 'Cymbalum électrique', value: 'electric_cimbalom' },
  { name: 'Guitare électrique', value: 'electric_guitar' },
  { name: 'Piano électrique', value: 'electric_piano' },
  { name: 'Erhu', value: 'erhu' },
  { name: 'Fiddle', value: 'fiddle' },
  { name: 'Folgerphone', value: 'folgerphone' },
  { name: 'Gayageum', value: 'gayageum' },
  { name: 'Ghatam', value: 'ghatam' },
  { name: 'Harmonica en verre', value: 'glass_harmonica' },
  { name: 'Glockenspiel', value: 'glockenspiel' },
  { name: 'Tambour à gobelet', value: 'goblet_drum' },
  { name: 'Gong', value: 'gong' },
  { name: 'Grand piano', value: 'grand_piano' },
  { name: 'Guan', value: 'guan' },
  { name: 'Guiro', value: 'guiro' },
  { name: 'Haegeum', value: 'haegeum' },
  { name: 'Cymbalum à marteaux', value: 'hammer_dulcimer' },
  { name: 'Orgue Hammond', value: 'hammond_organ' },
  { name: 'Harmonica', value: 'harmonica' },
  { name: 'Harmonium', value: 'harmonium' },
  { name: 'Guitare harpe', value: 'harp_guitar' },
  { name: 'Guitare harpe B', value: 'harp_guitar_b' },
  { name: 'Harpe', value: 'harp' },
  { name: 'Clavecin', value: 'harpsichord' },
  { name: 'Guitare hawaïenne', value: 'hawaii_guitar' },
  { name: 'Hellertion', value: 'hellertion' },
  { name: 'Horagai', value: 'horagai' },
  { name: 'Cor', value: 'horn' },
  { name: 'Hotchiku', value: 'hotchiku' },
  { name: 'Vielle à roue', value: 'hurdy_gurdy' },
  { name: 'Jeu de jazz', value: 'jazz_set' },
  { name: 'Guimbarde', value: 'jews_harp' },
  { name: 'Grelots', value: 'jingle_bells' },
  { name: 'Kantele', value: 'kantele' },
  { name: 'Ken bau', value: 'ken_bau' },
  { name: 'Tympan', value: 'kettle_drum' },
  { name: 'Clairon à clés', value: 'keyed_bugle' },
  { name: 'Khene', value: 'khene' },
  { name: 'Khloy', value: 'khloy' },
  { name: 'Khlui', value: 'khlui' },
  { name: 'Kobza', value: 'kobza' },
  { name: 'Koudi', value: 'koudi' },
  { name: 'Launeddas', value: 'launeddas' },
  { name: 'Linguaphone', value: 'linguaphone' },
  { name: 'Lusheng', value: 'lusheng' },
  { name: 'Mandocello', value: 'mandocello' },
  { name: 'Mandoline', value: 'mandolin' },
  { name: 'Maracas', value: 'maraca' },
  { name: 'Mélodéon', value: 'melodeon' },
  { name: 'Mélodica', value: 'melodica' },
  { name: 'Métronome', value: 'metronome' },
  { name: 'Mijwiz', value: 'mijwiz' },
  { name: 'Mridangam', value: 'mridangam' },
  { name: 'Multimonica', value: 'multimonica' },
  { name: 'Muyu', value: 'muyu' },
  { name: 'Naal', value: 'naal' },
  { name: 'Nadaswaram', value: 'nadaswaram' },
  { name: 'Nadara', value: 'nagara' },
  { name: 'Flûte nasale', value: 'nose_flute' },
  { name: 'Nyckelharpa', value: 'nyckelharpa' },
  { name: 'ObeoDaCaccia', value: 'oboe_da_caccia' },
  { name: 'ObeoDamore', value: 'oboe_damore' },
  { name: 'Ocarina', value: 'ocarina' },
  { name: 'Octapad', value: 'octapad' },
  { name: 'Octavin', value: 'octavin' },
  { name: 'Octoban', value: 'octoban' },
  { name: 'Octo-clarinette alto', value: 'octocontralto_clarinet' },
  { name: 'Ophicléide', value: 'ophicleide' },
  { name: 'Orgue', value: 'organ' },
  { name: 'Oud', value: 'oud' },
  { name: 'Paixiao', value: 'paixiao' },
  { name: 'Palendag', value: 'palendag' },
  { name: 'Flûte de Pan', value: 'panpipes' },
  { name: 'Pengling', value: 'pengling' },
  { name: 'Piano', value: 'piano' },
  { name: 'Pibgorn', value: 'pibgorn' },
  { name: 'Guitare Picasso', value: 'picasso_guitar' },
  { name: 'Clarinette piccolo', value: 'piccolo_clarinet' },
  { name: 'Heckelphone piccolo', value: 'piccolo_heckelphone' },
  { name: 'Hautbois piccolo', value: 'piccolo_oboe' },
  { name: 'Orgue à tuyaux', value: 'pipe_organ' },
  { name: 'Pyrophone', value: 'pyrophone' },
  { name: 'Quena', value: 'quena' },
  { name: 'Quinticlave', value: 'quinticlave' },
  { name: 'Rackett', value: 'rackett' },
  { name: 'Rebec', value: 'rebec' },
  { name: 'Contrebasse à anche', value: 'reed_contrabass' },
  { name: 'Guitare à résonateur', value: 'resonator_guitar' },
  { name: 'Guitare rock', value: 'rock_guitar' },
  { name: 'Saenghwang', value: 'saenghwang' },
  { name: 'Salamiyyah', value: 'salamiyyah' },
  { name: 'Santoor', value: 'santoor' },
  { name: 'Saxie', value: 'saxie' },
  { name: 'Saxonette', value: 'saxonette' },
  { name: 'Saxophone', value: 'saxophone' },
  { name: 'Serpent', value: 'serpent' },
  { name: 'Shekere', value: 'shekere' },
  { name: 'Sheng', value: 'sheng' },
  { name: 'Shinobue', value: 'shinobue' },
  { name: 'Shofar', value: 'shofar' },
  { name: 'Bol chantant', value: 'singing_bowl' },
  { name: 'Sitar', value: 'sitar' },
  { name: 'Guitare slide', value: 'slide_guitar' },
  { name: 'Sifflet à coulisse', value: 'slide_whistle' },
  { name: 'Tambour fendu', value: 'slit_drum' },
  { name: 'Caisse claire', value: 'snare' },
  { name: 'Clarinette soprano', value: 'soprano_clarinet' },
  { name: 'Sarrusophone soprano', value: 'soprano_sarrusophone' },
  { name: 'Saxophone soprano', value: 'soprano_saxophone' },
  { name: 'Soprillo', value: 'soprillo' },
  { name: 'Sousaphone', value: 'sousaphone' },
  { name: 'Guitare espagnole', value: 'spanish_guitar' },
  { name: 'Sralai', value: 'sralai' },
  { name: 'Steel Drum', value: 'steel_drum' },
  { name: 'Guitare steel', value: 'steel_guitar' },
  { name: 'Stylophone', value: 'stylophone' },
  { name: 'Flûte sub-contrebasse', value: 'subcontrabass_flute' },
  { name: 'Suling', value: 'suling' },
  { name: 'Suona', value: 'suona' },
  { name: 'Surnay', value: 'surnay' },
  { name: 'Synthétiseur', value: 'synthesizer' },
  { name: 'Tabla', value: 'tabla' },
  { name: 'Tambourin', value: 'tambourine' },
  { name: 'Tanpura', value: 'tanpura' },
  { name: 'Tarogato', value: 'tarogato' },
  { name: 'Cor ténor', value: 'tenor_horn' },
  { name: 'Tenori-On', value: 'tenori_on' },
  { name: 'Ténoroon', value: 'tenoroon' },
  { name: 'Heckelphone terz', value: 'terz_heckelphone' },
  { name: 'Thérémine', value: 'theremin' },
  { name: 'Sifflet en étain', value: 'tin_whistle' },
  { name: 'Tonette', value: 'tonette' },
  { name: 'Triangle', value: 'triangle' },
  { name: 'Carillon tubulaire', value: 'tubular_bells' },
  { name: 'Tumpong', value: 'tumpong' },
  { name: 'Diapason', value: 'tuning_fork' },
  { name: 'Udu', value: 'udu' },
  { name: 'Ukulélé', value: 'ukulele' },
  { name: 'Univox', value: 'univox' },
  { name: 'Piano droit', value: 'upright_piano' },
  { name: 'Veena', value: 'veena' },
  { name: 'Flûte verticale', value: 'vertical_flute' },
  { name: 'Vibraphone', value: 'vibraphone' },
  { name: 'Violon', value: 'violin' },
  { name: 'Tuba de Wagner', value: 'wagner_tuba' },
  { name: 'Planche à laver', value: 'washboard' },
  { name: 'Washint', value: 'washint' },
  { name: "Flûte d'eau", value: 'waterflute' },
  { name: 'Sifflet', value: 'whistle' },
  { name: 'Flûte de saule', value: 'willow_flute' },
  { name: 'Xun', value: 'xun' },
  { name: 'Xylophone', value: 'xylophone' },
  { name: 'Cithare', value: 'zither' },
  { name: 'Zufolo', value: 'zufolo' },
];

export default instruments;
