/* eslint-disable camelcase */
import type { Language } from '../../types/language.type';

export const languages: Language[] = [
  {
    english: 'Afar',
    french: 'afar',
    alpha2: 'aa',
    alpha3_b: 'aar',
    alpha3_t: '',
  },
  {
    english: 'Abkhazian',
    french: 'abkhaze',
    alpha2: 'ab',
    alpha3_b: 'abk',
    alpha3_t: '',
  },
  {
    english: 'Achinese',
    french: 'aceh',
    alpha2: '',
    alpha3_b: 'ace',
    alpha3_t: '',
  },
  {
    english: 'Acoli',
    french: 'acoli',
    alpha2: '',
    alpha3_b: 'ach',
    alpha3_t: '',
  },
  {
    english: 'Adangme',
    french: 'adangme',
    alpha2: '',
    alpha3_b: 'ada',
    alpha3_t: '',
  },
  {
    english: 'Adyghe; Adygei',
    french: 'adyghé',
    alpha2: '',
    alpha3_b: 'ady',
    alpha3_t: '',
  },
  {
    english: 'Afrihili',
    french: 'afrihili',
    alpha2: '',
    alpha3_b: 'afh',
    alpha3_t: '',
  },
  {
    english: 'Afrikaans',
    french: 'afrikaans',
    alpha2: 'af',
    alpha3_b: 'afr',
    alpha3_t: '',
  },
  {
    english: 'Ainu',
    french: 'aïnou',
    alpha2: '',
    alpha3_b: 'ain',
    alpha3_t: '',
  },
  {
    english: 'Akan',
    french: 'akan',
    alpha2: 'ak',
    alpha3_b: 'aka',
    alpha3_t: '',
  },
  {
    english: 'Akkadian',
    french: 'akkadien',
    alpha2: '',
    alpha3_b: 'akk',
    alpha3_t: '',
  },
  {
    english: 'Albanian',
    french: 'albanais',
    alpha2: 'sq',
    alpha3_b: 'alb',
    alpha3_t: 'sqi',
  },
  {
    english: 'Aleut',
    french: 'aléoute',
    alpha2: '',
    alpha3_b: 'ale',
    alpha3_t: '',
  },
  {
    english: 'Southern Altai',
    french: 'altai du Sud',
    alpha2: '',
    alpha3_b: 'alt',
    alpha3_t: '',
  },
  {
    english: 'Amharic',
    french: 'amharique',
    alpha2: 'am',
    alpha3_b: 'amh',
    alpha3_t: '',
  },
  {
    english: 'Angika',
    french: 'angika',
    alpha2: '',
    alpha3_b: 'anp',
    alpha3_t: '',
  },
  {
    english: 'Arabic',
    french: 'arabe',
    alpha2: 'ar',
    alpha3_b: 'ara',
    alpha3_t: '',
  },
  {
    english: 'Aragonese',
    french: 'aragonais',
    alpha2: 'an',
    alpha3_b: 'arg',
    alpha3_t: '',
  },
  {
    english: 'Armenian',
    french: 'arménien',
    alpha2: 'hy',
    alpha3_b: 'arm',
    alpha3_t: 'hye',
  },
  {
    english: 'Mapudungun; Mapuche',
    french: 'mapudungun; mapuche; mapuce',
    alpha2: '',
    alpha3_b: 'arn',
    alpha3_t: '',
  },
  {
    english: 'Arapaho',
    french: 'arapaho',
    alpha2: '',
    alpha3_b: 'arp',
    alpha3_t: '',
  },
  {
    english: 'Arawak',
    french: 'arawak',
    alpha2: '',
    alpha3_b: 'arw',
    alpha3_t: '',
  },
  {
    english: 'Assamese',
    french: 'assamais',
    alpha2: 'as',
    alpha3_b: 'asm',
    alpha3_t: '',
  },
  {
    english: 'Avaric',
    french: 'avar',
    alpha2: 'av',
    alpha3_b: 'ava',
    alpha3_t: '',
  },
  {
    english: 'Avestan',
    french: 'avestique',
    alpha2: 'ae',
    alpha3_b: 'ave',
    alpha3_t: '',
  },
  {
    english: 'Awadhi',
    french: 'awadhi',
    alpha2: '',
    alpha3_b: 'awa',
    alpha3_t: '',
  },
  {
    english: 'Aymara',
    french: 'aymara',
    alpha2: 'ay',
    alpha3_b: 'aym',
    alpha3_t: '',
  },
  {
    english: 'Azerbaijani',
    french: 'azéri',
    alpha2: 'az',
    alpha3_b: 'aze',
    alpha3_t: '',
  },
  {
    english: 'Bashkir',
    french: 'bachkir',
    alpha2: 'ba',
    alpha3_b: 'bak',
    alpha3_t: '',
  },
  {
    english: 'Baluchi',
    french: 'baloutchi',
    alpha2: '',
    alpha3_b: 'bal',
    alpha3_t: '',
  },
  {
    english: 'Bambara',
    french: 'bambara',
    alpha2: 'bm',
    alpha3_b: 'bam',
    alpha3_t: '',
  },
  {
    english: 'Balinese',
    french: 'balinais',
    alpha2: '',
    alpha3_b: 'ban',
    alpha3_t: '',
  },
  {
    english: 'Basque',
    french: 'basque',
    alpha2: 'eu',
    alpha3_b: 'baq',
    alpha3_t: 'eus',
  },
  {
    english: 'Basa',
    french: 'basa',
    alpha2: '',
    alpha3_b: 'bas',
    alpha3_t: '',
  },
  {
    english: 'Beja; Bedawiyet',
    french: 'bedja',
    alpha2: '',
    alpha3_b: 'bej',
    alpha3_t: '',
  },
  {
    english: 'Belarusian',
    french: 'biélorusse',
    alpha2: 'be',
    alpha3_b: 'bel',
    alpha3_t: '',
  },
  {
    english: 'Bemba',
    french: 'bemba',
    alpha2: '',
    alpha3_b: 'bem',
    alpha3_t: '',
  },
  {
    english: 'Bengali',
    french: 'bengali',
    alpha2: 'bn',
    alpha3_b: 'ben',
    alpha3_t: '',
  },
  {
    english: 'Bhojpuri',
    french: 'bhojpuri',
    alpha2: '',
    alpha3_b: 'bho',
    alpha3_t: '',
  },
  {
    english: 'Bikol',
    french: 'bikol',
    alpha2: '',
    alpha3_b: 'bik',
    alpha3_t: '',
  },
  {
    english: 'Bini; Edo',
    french: 'bini; edo',
    alpha2: '',
    alpha3_b: 'bin',
    alpha3_t: '',
  },
  {
    english: 'Bislama',
    french: 'bichlamar',
    alpha2: 'bi',
    alpha3_b: 'bis',
    alpha3_t: '',
  },
  {
    english: 'Siksika',
    french: 'blackfoot',
    alpha2: '',
    alpha3_b: 'bla',
    alpha3_t: '',
  },
  {
    english: 'Bosnian',
    french: 'bosniaque',
    alpha2: 'bs',
    alpha3_b: 'bos',
    alpha3_t: '',
  },
  {
    english: 'Braj',
    french: 'braj',
    alpha2: '',
    alpha3_b: 'bra',
    alpha3_t: '',
  },
  {
    english: 'Breton',
    french: 'breton',
    alpha2: 'br',
    alpha3_b: 'bre',
    alpha3_t: '',
  },
  {
    english: 'Buriat',
    french: 'bouriate',
    alpha2: '',
    alpha3_b: 'bua',
    alpha3_t: '',
  },
  {
    english: 'Buginese',
    french: 'bugi',
    alpha2: '',
    alpha3_b: 'bug',
    alpha3_t: '',
  },
  {
    english: 'Bulgarian',
    french: 'bulgare',
    alpha2: 'bg',
    alpha3_b: 'bul',
    alpha3_t: '',
  },
  {
    english: 'Burmese',
    french: 'birman',
    alpha2: 'my',
    alpha3_b: 'bur',
    alpha3_t: 'mya',
  },
  {
    english: 'Blin; Bilin',
    french: 'blin; bilen',
    alpha2: '',
    alpha3_b: 'byn',
    alpha3_t: '',
  },
  {
    english: 'Caddo',
    french: 'caddo',
    alpha2: '',
    alpha3_b: 'cad',
    alpha3_t: '',
  },
  {
    english: 'Galibi Carib',
    french: 'karib; galibi; carib',
    alpha2: '',
    alpha3_b: 'car',
    alpha3_t: '',
  },
  {
    english: 'Catalan; Valencian',
    french: 'catalan; valencien',
    alpha2: 'ca',
    alpha3_b: 'cat',
    alpha3_t: '',
  },
  {
    english: 'Cebuano',
    french: 'cebuano',
    alpha2: '',
    alpha3_b: 'ceb',
    alpha3_t: '',
  },
  {
    english: 'Chamorro',
    french: 'chamorro',
    alpha2: 'ch',
    alpha3_b: 'cha',
    alpha3_t: '',
  },
  {
    english: 'Chibcha',
    french: 'chibcha',
    alpha2: '',
    alpha3_b: 'chb',
    alpha3_t: '',
  },
  {
    english: 'Chechen',
    french: 'tchétchène',
    alpha2: 'ce',
    alpha3_b: 'che',
    alpha3_t: '',
  },
  {
    english: 'Chagatai',
    french: 'djaghataï',
    alpha2: '',
    alpha3_b: 'chg',
    alpha3_t: '',
  },
  {
    english: 'Chinese',
    french: 'chinois',
    alpha2: 'zh',
    alpha3_b: 'chi',
    alpha3_t: 'zho',
  },
  {
    english: 'Chuukese',
    french: 'chuuk',
    alpha2: '',
    alpha3_b: 'chk',
    alpha3_t: '',
  },
  {
    english: 'Mari',
    french: 'mari',
    alpha2: '',
    alpha3_b: 'chm',
    alpha3_t: '',
  },
  {
    english: 'Chinook jargon',
    french: 'chinook, jargon',
    alpha2: '',
    alpha3_b: 'chn',
    alpha3_t: '',
  },
  {
    english: 'Choctaw',
    french: 'choctaw',
    alpha2: '',
    alpha3_b: 'cho',
    alpha3_t: '',
  },
  {
    english: 'Chipewyan; Dene Suline',
    french: 'chipewyan',
    alpha2: '',
    alpha3_b: 'chp',
    alpha3_t: '',
  },
  {
    english: 'Cherokee',
    french: 'cherokee',
    alpha2: '',
    alpha3_b: 'chr',
    alpha3_t: '',
  },
  {
    english: 'Chuvash',
    french: 'tchouvache',
    alpha2: 'cv',
    alpha3_b: 'chv',
    alpha3_t: '',
  },
  {
    english: 'Cheyenne',
    french: 'cheyenne',
    alpha2: '',
    alpha3_b: 'chy',
    alpha3_t: '',
  },
  {
    english: 'Montenegrin',
    french: 'monténégrin',
    alpha2: '',
    alpha3_b: 'cnr',
    alpha3_t: '',
  },
  {
    english: 'Coptic',
    french: 'copte',
    alpha2: '',
    alpha3_b: 'cop',
    alpha3_t: '',
  },
  {
    english: 'Cornish',
    french: 'cornique',
    alpha2: 'kw',
    alpha3_b: 'cor',
    alpha3_t: '',
  },
  {
    english: 'Corsican',
    french: 'corse',
    alpha2: 'co',
    alpha3_b: 'cos',
    alpha3_t: '',
  },
  {
    english: 'Creoles and pidgins, english based',
    french: "créoles et pidgins basés sur l'anglais",
    alpha2: '',
    alpha3_b: 'cpe',
    alpha3_t: '',
  },
  {
    english: 'Creoles and pidgins, french-based',
    french: 'créoles et pidgins basés sur le français',
    alpha2: '',
    alpha3_b: 'cpf',
    alpha3_t: '',
  },
  {
    english: 'Creoles and pidgins, Portuguese-based',
    french: 'créoles et pidgins basés sur le portugais',
    alpha2: '',
    alpha3_b: 'cpp',
    alpha3_t: '',
  },
  {
    english: 'Cree',
    french: 'cree',
    alpha2: 'cr',
    alpha3_b: 'cre',
    alpha3_t: '',
  },
  {
    english: 'Crimean Tatar; Crimean Turkish',
    french: 'tatar de Crimé',
    alpha2: '',
    alpha3_b: 'crh',
    alpha3_t: '',
  },
  {
    english: 'Creoles and pidgins',
    french: 'créoles et pidgins',
    alpha2: '',
    alpha3_b: 'crp',
    alpha3_t: '',
  },
  {
    english: 'Kashubian',
    french: 'kachoube',
    alpha2: '',
    alpha3_b: 'csb',
    alpha3_t: '',
  },
  {
    english: 'Czech',
    french: 'tchèque',
    alpha2: 'cs',
    alpha3_b: 'cze',
    alpha3_t: 'ces',
  },
  {
    english: 'Dakota',
    french: 'dakota',
    alpha2: '',
    alpha3_b: 'dak',
    alpha3_t: '',
  },
  {
    english: 'Danish',
    french: 'danois',
    alpha2: 'da',
    alpha3_b: 'dan',
    alpha3_t: '',
  },
  {
    english: 'Dargwa',
    french: 'dargwa',
    alpha2: '',
    alpha3_b: 'dar',
    alpha3_t: '',
  },
  {
    english: 'Delaware',
    french: 'delaware',
    alpha2: '',
    alpha3_b: 'del',
    alpha3_t: '',
  },
  {
    english: 'Slave (Athapascan)',
    french: 'esclave (athapascan)',
    alpha2: '',
    alpha3_b: 'den',
    alpha3_t: '',
  },
  {
    english: 'Dogrib',
    french: 'dogrib',
    alpha2: '',
    alpha3_b: 'dgr',
    alpha3_t: '',
  },
  {
    english: 'Dinka',
    french: 'dinka',
    alpha2: '',
    alpha3_b: 'din',
    alpha3_t: '',
  },
  {
    english: 'Divehi; Dhivehi; Maldivian',
    french: 'maldivien',
    alpha2: 'dv',
    alpha3_b: 'div',
    alpha3_t: '',
  },
  {
    english: 'Dogri',
    french: 'dogri',
    alpha2: '',
    alpha3_b: 'doi',
    alpha3_t: '',
  },
  {
    english: 'Lower Sorbian',
    french: 'bas-sorabe',
    alpha2: '',
    alpha3_b: 'dsb',
    alpha3_t: '',
  },
  {
    english: 'Duala',
    french: 'douala',
    alpha2: '',
    alpha3_b: 'dua',
    alpha3_t: '',
  },
  {
    english: 'Dutch; Flemish',
    french: 'néerlandais; flamand',
    alpha2: 'nl',
    alpha3_b: 'dut',
    alpha3_t: 'nld',
  },
  {
    english: 'Dyula',
    french: 'dioula',
    alpha2: '',
    alpha3_b: 'dyu',
    alpha3_t: '',
  },
  {
    english: 'Dzongkha',
    french: 'dzongkha',
    alpha2: 'dz',
    alpha3_b: 'dzo',
    alpha3_t: '',
  },
  {
    english: 'Efik',
    french: 'efik',
    alpha2: '',
    alpha3_b: 'efi',
    alpha3_t: '',
  },
  {
    english: 'Egyptian (Ancient)',
    french: 'égyptien',
    alpha2: '',
    alpha3_b: 'egy',
    alpha3_t: '',
  },
  {
    english: 'Ekajuk',
    french: 'ekajuk',
    alpha2: '',
    alpha3_b: 'eka',
    alpha3_t: '',
  },
  {
    english: 'Elamite',
    french: 'élamite',
    alpha2: '',
    alpha3_b: 'elx',
    alpha3_t: '',
  },
  {
    english: 'english',
    french: 'anglais',
    alpha2: 'en',
    alpha3_b: 'eng',
    alpha3_t: '',
  },
  {
    english: 'Esperanto',
    french: 'espéranto',
    alpha2: 'eo',
    alpha3_b: 'epo',
    alpha3_t: '',
  },
  {
    english: 'Estonian',
    french: 'estonien',
    alpha2: 'et',
    alpha3_b: 'est',
    alpha3_t: '',
  },
  {
    english: 'Ewe',
    french: 'éwé',
    alpha2: 'ee',
    alpha3_b: 'ewe',
    alpha3_t: '',
  },
  {
    english: 'Ewondo',
    french: 'éwondo',
    alpha2: '',
    alpha3_b: 'ewo',
    alpha3_t: '',
  },
  {
    english: 'Fang',
    french: 'fang',
    alpha2: '',
    alpha3_b: 'fan',
    alpha3_t: '',
  },
  {
    english: 'Faroese',
    french: 'féroïen',
    alpha2: 'fo',
    alpha3_b: 'fao',
    alpha3_t: '',
  },
  {
    english: 'Fanti',
    french: 'fanti',
    alpha2: '',
    alpha3_b: 'fat',
    alpha3_t: '',
  },
  {
    english: 'Fijian',
    french: 'fidjien',
    alpha2: 'fj',
    alpha3_b: 'fij',
    alpha3_t: '',
  },
  {
    english: 'Filipino; Pilipino',
    french: 'filipino; pilipino',
    alpha2: '',
    alpha3_b: 'fil',
    alpha3_t: '',
  },
  {
    english: 'Finnish',
    french: 'finnois',
    alpha2: 'fi',
    alpha3_b: 'fin',
    alpha3_t: '',
  },
  {
    english: 'Fon',
    french: 'fon',
    alpha2: '',
    alpha3_b: 'fon',
    alpha3_t: '',
  },
  {
    english: 'french',
    french: 'français',
    alpha2: 'fr',
    alpha3_b: 'fre',
    alpha3_t: 'fra',
  },
  {
    english: 'Northern Frisian',
    french: 'frison septentrional',
    alpha2: '',
    alpha3_b: 'frr',
    alpha3_t: '',
  },
  {
    english: 'Eastern Frisian',
    french: 'frison oriental',
    alpha2: '',
    alpha3_b: 'frs',
    alpha3_t: '',
  },
  {
    english: 'Western Frisian',
    french: 'frison occidental',
    alpha2: 'fy',
    alpha3_b: 'fry',
    alpha3_t: '',
  },
  {
    english: 'Fulah',
    french: 'peul',
    alpha2: 'ff',
    alpha3_b: 'ful',
    alpha3_t: '',
  },
  {
    english: 'Friulian',
    french: 'frioulan',
    alpha2: '',
    alpha3_b: 'fur',
    alpha3_t: '',
  },
  {
    english: 'Ga',
    french: 'ga',
    alpha2: '',
    alpha3_b: 'gaa',
    alpha3_t: '',
  },
  {
    english: 'Gayo',
    french: 'gayo',
    alpha2: '',
    alpha3_b: 'gay',
    alpha3_t: '',
  },
  {
    english: 'Gbaya',
    french: 'gbaya',
    alpha2: '',
    alpha3_b: 'gba',
    alpha3_t: '',
  },
  {
    english: 'Georgian',
    french: 'géorgien',
    alpha2: 'ka',
    alpha3_b: 'geo',
    alpha3_t: 'kat',
  },
  {
    english: 'German',
    french: 'allemand',
    alpha2: 'de',
    alpha3_b: 'ger',
    alpha3_t: 'deu',
  },
  {
    english: 'Geez',
    french: 'guèze',
    alpha2: '',
    alpha3_b: 'gez',
    alpha3_t: '',
  },
  {
    english: 'Gilbertese',
    french: 'kiribati',
    alpha2: '',
    alpha3_b: 'gil',
    alpha3_t: '',
  },
  {
    english: 'Gaelic; Scottish Gaelic',
    french: 'gaélique; gaélique écossais',
    alpha2: 'gd',
    alpha3_b: 'gla',
    alpha3_t: '',
  },
  {
    english: 'Irish',
    french: 'irlandais',
    alpha2: 'ga',
    alpha3_b: 'gle',
    alpha3_t: '',
  },
  {
    english: 'Galician',
    french: 'galicien',
    alpha2: 'gl',
    alpha3_b: 'glg',
    alpha3_t: '',
  },
  {
    english: 'Manx',
    french: 'manx; mannois',
    alpha2: 'gv',
    alpha3_b: 'glv',
    alpha3_t: '',
  },
  {
    english: 'Gondi',
    french: 'gond',
    alpha2: '',
    alpha3_b: 'gon',
    alpha3_t: '',
  },
  {
    english: 'Gorontalo',
    french: 'gorontalo',
    alpha2: '',
    alpha3_b: 'gor',
    alpha3_t: '',
  },
  {
    english: 'Gothic',
    french: 'gothique',
    alpha2: '',
    alpha3_b: 'got',
    alpha3_t: '',
  },
  {
    english: 'Grebo',
    french: 'grebo',
    alpha2: '',
    alpha3_b: 'grb',
    alpha3_t: '',
  },
  {
    english: 'Greek, Ancient (to 1453)',
    french: "grec ancien (jusqu'à 1453)",
    alpha2: '',
    alpha3_b: 'grc',
    alpha3_t: '',
  },
  {
    english: 'Greek, Modern (1453-)',
    french: 'grec moderne (après 1453)',
    alpha2: 'el',
    alpha3_b: 'gre',
    alpha3_t: 'ell',
  },
  {
    english: 'Guarani',
    french: 'guarani',
    alpha2: 'gn',
    alpha3_b: 'grn',
    alpha3_t: '',
  },
  {
    english: 'Swiss German; Alemannic; Alsatian',
    french: 'suisse alémanique; alémanique; alsacien',
    alpha2: '',
    alpha3_b: 'gsw',
    alpha3_t: '',
  },
  {
    english: 'Gujarati',
    french: 'goudjrati',
    alpha2: 'gu',
    alpha3_b: 'guj',
    alpha3_t: '',
  },
  {
    english: "Gwich'in",
    french: "gwich'in",
    alpha2: '',
    alpha3_b: 'gwi',
    alpha3_t: '',
  },
  {
    english: 'Haida',
    french: 'haida',
    alpha2: '',
    alpha3_b: 'hai',
    alpha3_t: '',
  },
  {
    english: 'Haitian; Haitian Creole',
    french: 'haïtien; créole haïtien',
    alpha2: 'ht',
    alpha3_b: 'hat',
    alpha3_t: '',
  },
  {
    english: 'Hausa',
    french: 'haoussa',
    alpha2: 'ha',
    alpha3_b: 'hau',
    alpha3_t: '',
  },
  {
    english: 'Hawaiian',
    french: 'hawaïen',
    alpha2: '',
    alpha3_b: 'haw',
    alpha3_t: '',
  },
  {
    english: 'Hebrew',
    french: 'hébreu',
    alpha2: 'he',
    alpha3_b: 'heb',
    alpha3_t: '',
  },
  {
    english: 'Herero',
    french: 'herero',
    alpha2: 'hz',
    alpha3_b: 'her',
    alpha3_t: '',
  },
  {
    english: 'Hiligaynon',
    french: 'hiligaynon',
    alpha2: '',
    alpha3_b: 'hil',
    alpha3_t: '',
  },
  {
    english: 'Hindi',
    french: 'hindi',
    alpha2: 'hi',
    alpha3_b: 'hin',
    alpha3_t: '',
  },
  {
    english: 'Hittite',
    french: 'hittite',
    alpha2: '',
    alpha3_b: 'hit',
    alpha3_t: '',
  },
  {
    english: 'Hmong; Mong',
    french: 'hmong',
    alpha2: '',
    alpha3_b: 'hmn',
    alpha3_t: '',
  },
  {
    english: 'Hiri Motu',
    french: 'hiri motu',
    alpha2: 'ho',
    alpha3_b: 'hmo',
    alpha3_t: '',
  },
  {
    english: 'Croatian',
    french: 'croate',
    alpha2: 'hr',
    alpha3_b: 'hrv',
    alpha3_t: '',
  },
  {
    english: 'Upper Sorbian',
    french: 'haut-sorabe',
    alpha2: '',
    alpha3_b: 'hsb',
    alpha3_t: '',
  },
  {
    english: 'Hungarian',
    french: 'hongrois',
    alpha2: 'hu',
    alpha3_b: 'hun',
    alpha3_t: '',
  },
  {
    english: 'Hupa',
    french: 'hupa',
    alpha2: '',
    alpha3_b: 'hup',
    alpha3_t: '',
  },
  {
    english: 'Iban',
    french: 'iban',
    alpha2: '',
    alpha3_b: 'iba',
    alpha3_t: '',
  },
  {
    english: 'Igbo',
    french: 'igbo',
    alpha2: 'ig',
    alpha3_b: 'ibo',
    alpha3_t: '',
  },
  {
    english: 'Icelandic',
    french: 'islandais',
    alpha2: 'is',
    alpha3_b: 'ice',
    alpha3_t: 'isl',
  },
  {
    english: 'Ido',
    french: 'ido',
    alpha2: 'io',
    alpha3_b: 'ido',
    alpha3_t: '',
  },
  {
    english: 'Sichuan Yi; Nuosu',
    french: 'yi de Sichuan',
    alpha2: 'ii',
    alpha3_b: 'iii',
    alpha3_t: '',
  },
  {
    english: 'Inuktitut',
    french: 'inuktitut',
    alpha2: 'iu',
    alpha3_b: 'iku',
    alpha3_t: '',
  },
  {
    english: 'Interlingue; Occidental',
    french: 'interlingue',
    alpha2: 'ie',
    alpha3_b: 'ile',
    alpha3_t: '',
  },
  {
    english: 'Iloko',
    french: 'ilocano',
    alpha2: '',
    alpha3_b: 'ilo',
    alpha3_t: '',
  },
  {
    english: 'Interlingua (International Auxiliary Language Association)',
    french: 'interlingua (langue auxiliaire internationale)',
    alpha2: 'ia',
    alpha3_b: 'ina',
    alpha3_t: '',
  },
  {
    english: 'Indonesian',
    french: 'indonésien',
    alpha2: 'id',
    alpha3_b: 'ind',
    alpha3_t: '',
  },
  {
    english: 'Ingush',
    french: 'ingouche',
    alpha2: '',
    alpha3_b: 'inh',
    alpha3_t: '',
  },
  {
    english: 'Inupiaq',
    french: 'inupiaq',
    alpha2: 'ik',
    alpha3_b: 'ipk',
    alpha3_t: '',
  },
  {
    english: 'Italian',
    french: 'italien',
    alpha2: 'it',
    alpha3_b: 'ita',
    alpha3_t: '',
  },
  {
    english: 'Javanese',
    french: 'javanais',
    alpha2: 'jv',
    alpha3_b: 'jav',
    alpha3_t: '',
  },
  {
    english: 'Lojban',
    french: 'lojban',
    alpha2: '',
    alpha3_b: 'jbo',
    alpha3_t: '',
  },
  {
    english: 'Japanese',
    french: 'japonais',
    alpha2: 'ja',
    alpha3_b: 'jpn',
    alpha3_t: '',
  },
  {
    english: 'Judeo-Persian',
    french: 'judéo-persan',
    alpha2: '',
    alpha3_b: 'jpr',
    alpha3_t: '',
  },
  {
    english: 'Judeo-Arabic',
    french: 'judéo-arabe',
    alpha2: '',
    alpha3_b: 'jrb',
    alpha3_t: '',
  },
  {
    english: 'Kara-Kalpak',
    french: 'karakalpak',
    alpha2: '',
    alpha3_b: 'kaa',
    alpha3_t: '',
  },
  {
    english: 'Kabyle',
    french: 'kabyle',
    alpha2: '',
    alpha3_b: 'kab',
    alpha3_t: '',
  },
  {
    english: 'Kachin; Jingpho',
    french: 'kachin; jingpho',
    alpha2: '',
    alpha3_b: 'kac',
    alpha3_t: '',
  },
  {
    english: 'Kalaallisut; Greenlandic',
    french: 'groenlandais',
    alpha2: 'kl',
    alpha3_b: 'kal',
    alpha3_t: '',
  },
  {
    english: 'Kamba',
    french: 'kamba',
    alpha2: '',
    alpha3_b: 'kam',
    alpha3_t: '',
  },
  {
    english: 'Kannada',
    french: 'kannada',
    alpha2: 'kn',
    alpha3_b: 'kan',
    alpha3_t: '',
  },
  {
    english: 'Kashmiri',
    french: 'kashmiri',
    alpha2: 'ks',
    alpha3_b: 'kas',
    alpha3_t: '',
  },
  {
    english: 'Kanuri',
    french: 'kanouri',
    alpha2: 'kr',
    alpha3_b: 'kau',
    alpha3_t: '',
  },
  {
    english: 'Kawi',
    french: 'kawi',
    alpha2: '',
    alpha3_b: 'kaw',
    alpha3_t: '',
  },
  {
    english: 'Kazakh',
    french: 'kazakh',
    alpha2: 'kk',
    alpha3_b: 'kaz',
    alpha3_t: '',
  },
  {
    english: 'Kabardian',
    french: 'kabardien',
    alpha2: '',
    alpha3_b: 'kbd',
    alpha3_t: '',
  },
  {
    english: 'Khasi',
    french: 'khasi',
    alpha2: '',
    alpha3_b: 'kha',
    alpha3_t: '',
  },
  {
    english: 'Central Khmer',
    french: 'khmer central',
    alpha2: 'km',
    alpha3_b: 'khm',
    alpha3_t: '',
  },
  {
    english: 'Khotanese; Sakan',
    french: 'khotanais; sakan',
    alpha2: '',
    alpha3_b: 'kho',
    alpha3_t: '',
  },
  {
    english: 'Kikuyu; Gikuyu',
    french: 'kikuyu',
    alpha2: 'ki',
    alpha3_b: 'kik',
    alpha3_t: '',
  },
  {
    english: 'Kinyarwanda',
    french: 'rwanda',
    alpha2: 'rw',
    alpha3_b: 'kin',
    alpha3_t: '',
  },
  {
    english: 'Kirghiz; Kyrgyz',
    french: 'kirghiz',
    alpha2: 'ky',
    alpha3_b: 'kir',
    alpha3_t: '',
  },
  {
    english: 'Kimbundu',
    french: 'kimbundu',
    alpha2: '',
    alpha3_b: 'kmb',
    alpha3_t: '',
  },
  {
    english: 'Konkani',
    french: 'konkani',
    alpha2: '',
    alpha3_b: 'kok',
    alpha3_t: '',
  },
  {
    english: 'Komi',
    french: 'kom',
    alpha2: 'kv',
    alpha3_b: 'kom',
    alpha3_t: '',
  },
  {
    english: 'Kongo',
    french: 'kongo',
    alpha2: 'kg',
    alpha3_b: 'kon',
    alpha3_t: '',
  },
  {
    english: 'Korean',
    french: 'coréen',
    alpha2: 'ko',
    alpha3_b: 'kor',
    alpha3_t: '',
  },
  {
    english: 'Kosraean',
    french: 'kosrae',
    alpha2: '',
    alpha3_b: 'kos',
    alpha3_t: '',
  },
  {
    english: 'Kpelle',
    french: 'kpellé',
    alpha2: '',
    alpha3_b: 'kpe',
    alpha3_t: '',
  },
  {
    english: 'Karachay-Balkar',
    french: 'karatchai balkar',
    alpha2: '',
    alpha3_b: 'krc',
    alpha3_t: '',
  },
  {
    english: 'Karelian',
    french: 'carélien',
    alpha2: '',
    alpha3_b: 'krl',
    alpha3_t: '',
  },
  {
    english: 'Kurukh',
    french: 'kurukh',
    alpha2: '',
    alpha3_b: 'kru',
    alpha3_t: '',
  },
  {
    english: 'Kuanyama; Kwanyama',
    french: 'kuanyama; kwanyama',
    alpha2: 'kj',
    alpha3_b: 'kua',
    alpha3_t: '',
  },
  {
    english: 'Kumyk',
    french: 'koumyk',
    alpha2: '',
    alpha3_b: 'kum',
    alpha3_t: '',
  },
  {
    english: 'Kurdish',
    french: 'kurde',
    alpha2: 'ku',
    alpha3_b: 'kur',
    alpha3_t: '',
  },
  {
    english: 'Kutenai',
    french: 'kutenai',
    alpha2: '',
    alpha3_b: 'kut',
    alpha3_t: '',
  },
  {
    english: 'Ladino',
    french: 'judéo-espagnol',
    alpha2: '',
    alpha3_b: 'lad',
    alpha3_t: '',
  },
  {
    english: 'Lahnda',
    french: 'lahnda',
    alpha2: '',
    alpha3_b: 'lah',
    alpha3_t: '',
  },
  {
    english: 'Lamba',
    french: 'lamba',
    alpha2: '',
    alpha3_b: 'lam',
    alpha3_t: '',
  },
  {
    english: 'Lao',
    french: 'lao',
    alpha2: 'lo',
    alpha3_b: 'lao',
    alpha3_t: '',
  },
  {
    english: 'Latin',
    french: 'latin',
    alpha2: 'la',
    alpha3_b: 'lat',
    alpha3_t: '',
  },
  {
    english: 'Latvian',
    french: 'letton',
    alpha2: 'lv',
    alpha3_b: 'lav',
    alpha3_t: '',
  },
  {
    english: 'Lezghian',
    french: 'lezghien',
    alpha2: '',
    alpha3_b: 'lez',
    alpha3_t: '',
  },
  {
    english: 'Limburgan; Limburger; Limburgish',
    french: 'limbourgeois',
    alpha2: 'li',
    alpha3_b: 'lim',
    alpha3_t: '',
  },
  {
    english: 'Lingala',
    french: 'lingala',
    alpha2: 'ln',
    alpha3_b: 'lin',
    alpha3_t: '',
  },
  {
    english: 'Lithuanian',
    french: 'lituanien',
    alpha2: 'lt',
    alpha3_b: 'lit',
    alpha3_t: '',
  },
  {
    english: 'Mongo',
    french: 'mongo',
    alpha2: '',
    alpha3_b: 'lol',
    alpha3_t: '',
  },
  {
    english: 'Lozi',
    french: 'lozi',
    alpha2: '',
    alpha3_b: 'loz',
    alpha3_t: '',
  },
  {
    english: 'Luxembourgish; Letzeburgesch',
    french: 'luxembourgeois',
    alpha2: 'lb',
    alpha3_b: 'ltz',
    alpha3_t: '',
  },
  {
    english: 'Luba-Lulua',
    french: 'luba-lulua',
    alpha2: '',
    alpha3_b: 'lua',
    alpha3_t: '',
  },
  {
    english: 'Luba-Katanga',
    french: 'luba-katanga',
    alpha2: 'lu',
    alpha3_b: 'lub',
    alpha3_t: '',
  },
  {
    english: 'Ganda',
    french: 'ganda',
    alpha2: 'lg',
    alpha3_b: 'lug',
    alpha3_t: '',
  },
  {
    english: 'Luiseno',
    french: 'luiseno',
    alpha2: '',
    alpha3_b: 'lui',
    alpha3_t: '',
  },
  {
    english: 'Lunda',
    french: 'lunda',
    alpha2: '',
    alpha3_b: 'lun',
    alpha3_t: '',
  },
  {
    english: 'Luo (Kenya and Tanzania)',
    french: 'luo (Kenya et Tanzanie)',
    alpha2: '',
    alpha3_b: 'luo',
    alpha3_t: '',
  },
  {
    english: 'Lushai',
    french: 'lushai',
    alpha2: '',
    alpha3_b: 'lus',
    alpha3_t: '',
  },
  {
    english: 'Macedonian',
    french: 'macédonien',
    alpha2: 'mk',
    alpha3_b: 'mac',
    alpha3_t: 'mkd',
  },
  {
    english: 'Madurese',
    french: 'madourais',
    alpha2: '',
    alpha3_b: 'mad',
    alpha3_t: '',
  },
  {
    english: 'Magahi',
    french: 'magahi',
    alpha2: '',
    alpha3_b: 'mag',
    alpha3_t: '',
  },
  {
    english: 'Marshallese',
    french: 'marshall',
    alpha2: 'mh',
    alpha3_b: 'mah',
    alpha3_t: '',
  },
  {
    english: 'Maithili',
    french: 'maithili',
    alpha2: '',
    alpha3_b: 'mai',
    alpha3_t: '',
  },
  {
    english: 'Makasar',
    french: 'makassar',
    alpha2: '',
    alpha3_b: 'mak',
    alpha3_t: '',
  },
  {
    english: 'Malayalam',
    french: 'malayalam',
    alpha2: 'ml',
    alpha3_b: 'mal',
    alpha3_t: '',
  },
  {
    english: 'Mandingo',
    french: 'mandingue',
    alpha2: '',
    alpha3_b: 'man',
    alpha3_t: '',
  },
  {
    english: 'Maori',
    french: 'maori',
    alpha2: 'mi',
    alpha3_b: 'mao',
    alpha3_t: 'mri',
  },
  {
    english: 'Marathi',
    french: 'marathe',
    alpha2: 'mr',
    alpha3_b: 'mar',
    alpha3_t: '',
  },
  {
    english: 'Masai',
    french: 'massaï',
    alpha2: '',
    alpha3_b: 'mas',
    alpha3_t: '',
  },
  {
    english: 'Malay',
    french: 'malais',
    alpha2: 'ms',
    alpha3_b: 'may',
    alpha3_t: 'msa',
  },
  {
    english: 'Moksha',
    french: 'moksa',
    alpha2: '',
    alpha3_b: 'mdf',
    alpha3_t: '',
  },
  {
    english: 'Mandar',
    french: 'mandar',
    alpha2: '',
    alpha3_b: 'mdr',
    alpha3_t: '',
  },
  {
    english: 'Mende',
    french: 'mendé',
    alpha2: '',
    alpha3_b: 'men',
    alpha3_t: '',
  },
  {
    english: "Mi'kmaq; Micmac",
    french: "mi'kmaq; micmac",
    alpha2: '',
    alpha3_b: 'mic',
    alpha3_t: '',
  },
  {
    english: 'Minangkabau',
    french: 'minangkabau',
    alpha2: '',
    alpha3_b: 'min',
    alpha3_t: '',
  },
  {
    english: 'Malagasy',
    french: 'malgache',
    alpha2: 'mg',
    alpha3_b: 'mlg',
    alpha3_t: '',
  },
  {
    english: 'Maltese',
    french: 'maltais',
    alpha2: 'mt',
    alpha3_b: 'mlt',
    alpha3_t: '',
  },
  {
    english: 'Manchu',
    french: 'mandchou',
    alpha2: '',
    alpha3_b: 'mnc',
    alpha3_t: '',
  },
  {
    english: 'Manipuri',
    french: 'manipuri',
    alpha2: '',
    alpha3_b: 'mni',
    alpha3_t: '',
  },
  {
    english: 'Mohawk',
    french: 'mohawk',
    alpha2: '',
    alpha3_b: 'moh',
    alpha3_t: '',
  },
  {
    english: 'Mongolian',
    french: 'mongol',
    alpha2: 'mn',
    alpha3_b: 'mon',
    alpha3_t: '',
  },
  {
    english: 'Mossi',
    french: 'moré',
    alpha2: '',
    alpha3_b: 'mos',
    alpha3_t: '',
  },
  {
    english: 'Creek',
    french: 'muskogee',
    alpha2: '',
    alpha3_b: 'mus',
    alpha3_t: '',
  },
  {
    english: 'Mirandese',
    french: 'mirandais',
    alpha2: '',
    alpha3_b: 'mwl',
    alpha3_t: '',
  },
  {
    english: 'Marwari',
    french: 'marvari',
    alpha2: '',
    alpha3_b: 'mwr',
    alpha3_t: '',
  },
  {
    english: 'Erzya',
    french: 'erza',
    alpha2: '',
    alpha3_b: 'myv',
    alpha3_t: '',
  },
  {
    english: 'Neapolitan',
    french: 'napolitain',
    alpha2: '',
    alpha3_b: 'nap',
    alpha3_t: '',
  },
  {
    english: 'Nauru',
    french: 'nauruan',
    alpha2: 'na',
    alpha3_b: 'nau',
    alpha3_t: '',
  },
  {
    english: 'Navajo; Navaho',
    french: 'navaho',
    alpha2: 'nv',
    alpha3_b: 'nav',
    alpha3_t: '',
  },
  {
    english: 'Ndebele, South; South Ndebele',
    french: 'ndébélé du Sud',
    alpha2: 'nr',
    alpha3_b: 'nbl',
    alpha3_t: '',
  },
  {
    english: 'Ndebele, North; North Ndebele',
    french: 'ndébélé du Nord',
    alpha2: 'nd',
    alpha3_b: 'nde',
    alpha3_t: '',
  },
  {
    english: 'Ndonga',
    french: 'ndonga',
    alpha2: 'ng',
    alpha3_b: 'ndo',
    alpha3_t: '',
  },
  {
    english: 'Nepali',
    french: 'népalais',
    alpha2: 'ne',
    alpha3_b: 'nep',
    alpha3_t: '',
  },
  {
    english: 'Nepal Bhasa; Newari',
    french: 'nepal bhasa; newari',
    alpha2: '',
    alpha3_b: 'new',
    alpha3_t: '',
  },
  {
    english: 'Nias',
    french: 'nias',
    alpha2: '',
    alpha3_b: 'nia',
    alpha3_t: '',
  },
  {
    english: 'Niuean',
    french: 'niué',
    alpha2: '',
    alpha3_b: 'niu',
    alpha3_t: '',
  },
  {
    english: 'Norwegian Nynorsk; Nynorsk, Norwegian',
    french: 'norvégien nynorsk; nynorsk, norvégien',
    alpha2: 'nn',
    alpha3_b: 'nno',
    alpha3_t: '',
  },
  {
    english: 'Bokmål, Norwegian; Norwegian Bokmål',
    french: 'norvégien bokmål',
    alpha2: 'nb',
    alpha3_b: 'nob',
    alpha3_t: '',
  },
  {
    english: 'Nogai',
    french: 'nogaï; nogay',
    alpha2: '',
    alpha3_b: 'nog',
    alpha3_t: '',
  },
  {
    english: 'Norse, Old',
    french: 'norrois, vieux',
    alpha2: '',
    alpha3_b: 'non',
    alpha3_t: '',
  },
  {
    english: 'Norwegian',
    french: 'norvégien',
    alpha2: 'no',
    alpha3_b: 'nor',
    alpha3_t: '',
  },
  {
    english: "N'Ko",
    french: "n'ko",
    alpha2: '',
    alpha3_b: 'nqo',
    alpha3_t: '',
  },
  {
    english: 'Pedi; Sepedi; Northern Sotho',
    french: 'pedi; sepedi; sotho du Nord',
    alpha2: '',
    alpha3_b: 'nso',
    alpha3_t: '',
  },
  {
    english: 'Classical Newari; Old Newari; Classical Nepal Bhasa',
    french: 'newari classique',
    alpha2: '',
    alpha3_b: 'nwc',
    alpha3_t: '',
  },
  {
    english: 'Chichewa; Chewa; Nyanja',
    french: 'chichewa; chewa; nyanja',
    alpha2: 'ny',
    alpha3_b: 'nya',
    alpha3_t: '',
  },
  {
    english: 'Nyamwezi',
    french: 'nyamwezi',
    alpha2: '',
    alpha3_b: 'nym',
    alpha3_t: '',
  },
  {
    english: 'Nyankole',
    french: 'nyankolé',
    alpha2: '',
    alpha3_b: 'nyn',
    alpha3_t: '',
  },
  {
    english: 'Nyoro',
    french: 'nyoro',
    alpha2: '',
    alpha3_b: 'nyo',
    alpha3_t: '',
  },
  {
    english: 'Nzima',
    french: 'nzema',
    alpha2: '',
    alpha3_b: 'nzi',
    alpha3_t: '',
  },
  {
    english: 'Occitan (post 1500)',
    french: 'occitan (après 1500)',
    alpha2: 'oc',
    alpha3_b: 'oci',
    alpha3_t: '',
  },
  {
    english: 'Ojibwa',
    french: 'ojibwa',
    alpha2: 'oj',
    alpha3_b: 'oji',
    alpha3_t: '',
  },
  {
    english: 'Oriya',
    french: 'oriya',
    alpha2: 'or',
    alpha3_b: 'ori',
    alpha3_t: '',
  },
  {
    english: 'Oromo',
    french: 'galla',
    alpha2: 'om',
    alpha3_b: 'orm',
    alpha3_t: '',
  },
  {
    english: 'Osage',
    french: 'osage',
    alpha2: '',
    alpha3_b: 'osa',
    alpha3_t: '',
  },
  {
    english: 'Ossetian; Ossetic',
    french: 'ossète',
    alpha2: 'os',
    alpha3_b: 'oss',
    alpha3_t: '',
  },
  {
    english: 'Turkish, Ottoman (1500-1928)',
    french: 'turc ottoman (1500-1928)',
    alpha2: '',
    alpha3_b: 'ota',
    alpha3_t: '',
  },
  {
    english: 'Pangasinan',
    french: 'pangasinan',
    alpha2: '',
    alpha3_b: 'pag',
    alpha3_t: '',
  },
  {
    english: 'Pahlavi',
    french: 'pahlavi',
    alpha2: '',
    alpha3_b: 'pal',
    alpha3_t: '',
  },
  {
    english: 'Pampanga; Kapampangan',
    french: 'pampangan',
    alpha2: '',
    alpha3_b: 'pam',
    alpha3_t: '',
  },
  {
    english: 'Panjabi; Punjabi',
    french: 'pendjabi',
    alpha2: 'pa',
    alpha3_b: 'pan',
    alpha3_t: '',
  },
  {
    english: 'Papiamento',
    french: 'papiamento',
    alpha2: '',
    alpha3_b: 'pap',
    alpha3_t: '',
  },
  {
    english: 'Palauan',
    french: 'palau',
    alpha2: '',
    alpha3_b: 'pau',
    alpha3_t: '',
  },
  {
    english: 'Persian',
    french: 'persan',
    alpha2: 'fa',
    alpha3_b: 'per',
    alpha3_t: 'fas',
  },
  {
    english: 'Phoenician',
    french: 'phénicien',
    alpha2: '',
    alpha3_b: 'phn',
    alpha3_t: '',
  },
  {
    english: 'Pali',
    french: 'pali',
    alpha2: 'pi',
    alpha3_b: 'pli',
    alpha3_t: '',
  },
  {
    english: 'Polish',
    french: 'polonais',
    alpha2: 'pl',
    alpha3_b: 'pol',
    alpha3_t: '',
  },
  {
    english: 'Pohnpeian',
    french: 'pohnpei',
    alpha2: '',
    alpha3_b: 'pon',
    alpha3_t: '',
  },
  {
    english: 'Portuguese',
    french: 'portugais',
    alpha2: 'pt',
    alpha3_b: 'por',
    alpha3_t: '',
  },
  {
    english: 'Provençal, Old (to 1500); Occitan, Old (to 1500)',
    french: "provençal ancien (jusqu'à 1500); occitan ancien (jusqu'à 1500)",
    alpha2: '',
    alpha3_b: 'pro',
    alpha3_t: '',
  },
  {
    english: 'Pushto; Pashto',
    french: 'pachto',
    alpha2: 'ps',
    alpha3_b: 'pus',
    alpha3_t: '',
  },
  {
    english: 'Quechua',
    french: 'quechua',
    alpha2: 'qu',
    alpha3_b: 'que',
    alpha3_t: '',
  },
  {
    english: 'Rajasthani',
    french: 'rajasthani',
    alpha2: '',
    alpha3_b: 'raj',
    alpha3_t: '',
  },
  {
    english: 'Rapanui',
    french: 'rapanui',
    alpha2: '',
    alpha3_b: 'rap',
    alpha3_t: '',
  },
  {
    english: 'Rarotongan; Cook Islands Maori',
    french: 'rarotonga; maori des îles Cook',
    alpha2: '',
    alpha3_b: 'rar',
    alpha3_t: '',
  },
  {
    english: 'Romansh',
    french: 'romanche',
    alpha2: 'rm',
    alpha3_b: 'roh',
    alpha3_t: '',
  },
  {
    english: 'Romany',
    french: 'tsigane',
    alpha2: '',
    alpha3_b: 'rom',
    alpha3_t: '',
  },
  {
    english: 'Romanian; Moldavian; Moldovan',
    french: 'roumain; moldave',
    alpha2: 'ro',
    alpha3_b: 'rum',
    alpha3_t: 'ron',
  },
  {
    english: 'Rundi',
    french: 'rundi',
    alpha2: 'rn',
    alpha3_b: 'run',
    alpha3_t: '',
  },
  {
    english: 'Russian',
    french: 'russe',
    alpha2: 'ru',
    alpha3_b: 'rus',
    alpha3_t: '',
  },
  {
    english: 'Sandawe',
    french: 'sandawe',
    alpha2: '',
    alpha3_b: 'sad',
    alpha3_t: '',
  },
  {
    english: 'Sango',
    french: 'sango',
    alpha2: 'sg',
    alpha3_b: 'sag',
    alpha3_t: '',
  },
  {
    english: 'Yakut',
    french: 'iakoute',
    alpha2: '',
    alpha3_b: 'sah',
    alpha3_t: '',
  },
  {
    english: 'Samaritan Aramaic',
    french: 'samaritain',
    alpha2: '',
    alpha3_b: 'sam',
    alpha3_t: '',
  },
  {
    english: 'Sanskrit',
    french: 'sanskrit',
    alpha2: 'sa',
    alpha3_b: 'san',
    alpha3_t: '',
  },
  {
    english: 'Sasak',
    french: 'sasak',
    alpha2: '',
    alpha3_b: 'sas',
    alpha3_t: '',
  },
  {
    english: 'Santali',
    french: 'santal',
    alpha2: '',
    alpha3_b: 'sat',
    alpha3_t: '',
  },
  {
    english: 'Sicilian',
    french: 'sicilien',
    alpha2: '',
    alpha3_b: 'scn',
    alpha3_t: '',
  },
  {
    english: 'Scots',
    french: 'écossais',
    alpha2: '',
    alpha3_b: 'sco',
    alpha3_t: '',
  },
  {
    english: 'Selkup',
    french: 'selkoupe',
    alpha2: '',
    alpha3_b: 'sel',
    alpha3_t: '',
  },
  {
    english: 'Sign Languages',
    french: 'langues des signes',
    alpha2: '',
    alpha3_b: 'sgn',
    alpha3_t: '',
  },
  {
    english: 'Shan',
    french: 'chan',
    alpha2: '',
    alpha3_b: 'shn',
    alpha3_t: '',
  },
  {
    english: 'Sidamo',
    french: 'sidamo',
    alpha2: '',
    alpha3_b: 'sid',
    alpha3_t: '',
  },
  {
    english: 'Sinhala; Sinhalese',
    french: 'singhalais',
    alpha2: 'si',
    alpha3_b: 'sin',
    alpha3_t: '',
  },
  {
    english: 'Slovak',
    french: 'slovaque',
    alpha2: 'sk',
    alpha3_b: 'slo',
    alpha3_t: 'slk',
  },
  {
    english: 'Slovenian',
    french: 'slovène',
    alpha2: 'sl',
    alpha3_b: 'slv',
    alpha3_t: '',
  },
  {
    english: 'Southern Sami',
    french: 'sami du Sud',
    alpha2: '',
    alpha3_b: 'sma',
    alpha3_t: '',
  },
  {
    english: 'Northern Sami',
    french: 'sami du Nord',
    alpha2: 'se',
    alpha3_b: 'sme',
    alpha3_t: '',
  },
  {
    english: 'Lule Sami',
    french: 'sami de Lule',
    alpha2: '',
    alpha3_b: 'smj',
    alpha3_t: '',
  },
  {
    english: 'Inari Sami',
    french: "sami d'Inari",
    alpha2: '',
    alpha3_b: 'smn',
    alpha3_t: '',
  },
  {
    english: 'Samoan',
    french: 'samoan',
    alpha2: 'sm',
    alpha3_b: 'smo',
    alpha3_t: '',
  },
  {
    english: 'Skolt Sami',
    french: 'sami skolt',
    alpha2: '',
    alpha3_b: 'sms',
    alpha3_t: '',
  },
  {
    english: 'Shona',
    french: 'shona',
    alpha2: 'sn',
    alpha3_b: 'sna',
    alpha3_t: '',
  },
  {
    english: 'Sindhi',
    french: 'sindhi',
    alpha2: 'sd',
    alpha3_b: 'snd',
    alpha3_t: '',
  },
  {
    english: 'Soninke',
    french: 'soninké',
    alpha2: '',
    alpha3_b: 'snk',
    alpha3_t: '',
  },
  {
    english: 'Sogdian',
    french: 'sogdien',
    alpha2: '',
    alpha3_b: 'sog',
    alpha3_t: '',
  },
  {
    english: 'Somali',
    french: 'somali',
    alpha2: 'so',
    alpha3_b: 'som',
    alpha3_t: '',
  },
  {
    english: 'Sotho, Southern',
    french: 'sotho du Sud',
    alpha2: 'st',
    alpha3_b: 'sot',
    alpha3_t: '',
  },
  {
    english: 'Spanish; Castilian',
    french: 'espagnol; castillan',
    alpha2: 'es',
    alpha3_b: 'spa',
    alpha3_t: '',
  },
  {
    english: 'Sardinian',
    french: 'sarde',
    alpha2: 'sc',
    alpha3_b: 'srd',
    alpha3_t: '',
  },
  {
    english: 'Sranan Tongo',
    french: 'sranan tongo',
    alpha2: '',
    alpha3_b: 'srn',
    alpha3_t: '',
  },
  {
    english: 'Serbian',
    french: 'serbe',
    alpha2: 'sr',
    alpha3_b: 'srp',
    alpha3_t: '',
  },
  {
    english: 'Serer',
    french: 'sérère',
    alpha2: '',
    alpha3_b: 'srr',
    alpha3_t: '',
  },
  {
    english: 'Swati',
    french: 'swati',
    alpha2: 'ss',
    alpha3_b: 'ssw',
    alpha3_t: '',
  },
  {
    english: 'Sukuma',
    french: 'sukuma',
    alpha2: '',
    alpha3_b: 'suk',
    alpha3_t: '',
  },
  {
    english: 'Sundanese',
    french: 'soundanais',
    alpha2: 'su',
    alpha3_b: 'sun',
    alpha3_t: '',
  },
  {
    english: 'Susu',
    french: 'soussou',
    alpha2: '',
    alpha3_b: 'sus',
    alpha3_t: '',
  },
  {
    english: 'Sumerian',
    french: 'sumérien',
    alpha2: '',
    alpha3_b: 'sux',
    alpha3_t: '',
  },
  {
    english: 'Swahili',
    french: 'swahili',
    alpha2: 'sw',
    alpha3_b: 'swa',
    alpha3_t: '',
  },
  {
    english: 'Swedish',
    french: 'suédois',
    alpha2: 'sv',
    alpha3_b: 'swe',
    alpha3_t: '',
  },
  {
    english: 'Syriac',
    french: 'syriaque',
    alpha2: '',
    alpha3_b: 'syr',
    alpha3_t: '',
  },
  {
    english: 'Tahitian',
    french: 'tahitien',
    alpha2: 'ty',
    alpha3_b: 'tah',
    alpha3_t: '',
  },
  {
    english: 'Tamil',
    french: 'tamoul',
    alpha2: 'ta',
    alpha3_b: 'tam',
    alpha3_t: '',
  },
  {
    english: 'Tatar',
    french: 'tatar',
    alpha2: 'tt',
    alpha3_b: 'tat',
    alpha3_t: '',
  },
  {
    english: 'Telugu',
    french: 'télougou',
    alpha2: 'te',
    alpha3_b: 'tel',
    alpha3_t: '',
  },
  {
    english: 'Timne',
    french: 'temne',
    alpha2: '',
    alpha3_b: 'tem',
    alpha3_t: '',
  },
  {
    english: 'Tereno',
    french: 'tereno',
    alpha2: '',
    alpha3_b: 'ter',
    alpha3_t: '',
  },
  {
    english: 'Tetum',
    french: 'tetum',
    alpha2: '',
    alpha3_b: 'tet',
    alpha3_t: '',
  },
  {
    english: 'Tajik',
    french: 'tadjik',
    alpha2: 'tg',
    alpha3_b: 'tgk',
    alpha3_t: '',
  },
  {
    english: 'Tagalog',
    french: 'tagalog',
    alpha2: 'tl',
    alpha3_b: 'tgl',
    alpha3_t: '',
  },
  {
    english: 'Thai',
    french: 'thaï',
    alpha2: 'th',
    alpha3_b: 'tha',
    alpha3_t: '',
  },
  {
    english: 'Tibetan',
    french: 'tibétain',
    alpha2: 'bo',
    alpha3_b: 'tib',
    alpha3_t: 'bod',
  },
  {
    english: 'Tigre',
    french: 'tigré',
    alpha2: '',
    alpha3_b: 'tig',
    alpha3_t: '',
  },
  {
    english: 'Tigrinya',
    french: 'tigrigna',
    alpha2: 'ti',
    alpha3_b: 'tir',
    alpha3_t: '',
  },
  {
    english: 'Tiv',
    french: 'tiv',
    alpha2: '',
    alpha3_b: 'tiv',
    alpha3_t: '',
  },
  {
    english: 'Tokelau',
    french: 'tokelau',
    alpha2: '',
    alpha3_b: 'tkl',
    alpha3_t: '',
  },
  {
    english: 'Klingon; tlhIngan-Hol',
    french: 'klingon',
    alpha2: '',
    alpha3_b: 'tlh',
    alpha3_t: '',
  },
  {
    english: 'Tlingit',
    french: 'tlingit',
    alpha2: '',
    alpha3_b: 'tli',
    alpha3_t: '',
  },
  {
    english: 'Tamashek',
    french: 'tamacheq',
    alpha2: '',
    alpha3_b: 'tmh',
    alpha3_t: '',
  },
  {
    english: 'Tonga (Nyasa)',
    french: 'tonga (Nyasa)',
    alpha2: '',
    alpha3_b: 'tog',
    alpha3_t: '',
  },
  {
    english: 'Tonga (Tonga Islands)',
    french: 'tongan (Îles Tonga)',
    alpha2: 'to',
    alpha3_b: 'ton',
    alpha3_t: '',
  },
  {
    english: 'Tok Pisin',
    french: 'tok pisin',
    alpha2: '',
    alpha3_b: 'tpi',
    alpha3_t: '',
  },
  {
    english: 'Tsimshian',
    french: 'tsimshian',
    alpha2: '',
    alpha3_b: 'tsi',
    alpha3_t: '',
  },
  {
    english: 'Tswana',
    french: 'tswana',
    alpha2: 'tn',
    alpha3_b: 'tsn',
    alpha3_t: '',
  },
  {
    english: 'Tsonga',
    french: 'tsonga',
    alpha2: 'ts',
    alpha3_b: 'tso',
    alpha3_t: '',
  },
  {
    english: 'Turkmen',
    french: 'turkmène',
    alpha2: 'tk',
    alpha3_b: 'tuk',
    alpha3_t: '',
  },
  {
    english: 'Tumbuka',
    french: 'tumbuka',
    alpha2: '',
    alpha3_b: 'tum',
    alpha3_t: '',
  },
  {
    english: 'Turkish',
    french: 'turc',
    alpha2: 'tr',
    alpha3_b: 'tur',
    alpha3_t: '',
  },
  {
    english: 'Tuvalu',
    french: 'tuvalu',
    alpha2: '',
    alpha3_b: 'tvl',
    alpha3_t: '',
  },
  {
    english: 'Twi',
    french: 'twi',
    alpha2: 'tw',
    alpha3_b: 'twi',
    alpha3_t: '',
  },
  {
    english: 'Tuvinian',
    french: 'touva',
    alpha2: '',
    alpha3_b: 'tyv',
    alpha3_t: '',
  },
  {
    english: 'Udmurt',
    french: 'oudmourte',
    alpha2: '',
    alpha3_b: 'udm',
    alpha3_t: '',
  },
  {
    english: 'Ugaritic',
    french: 'ougaritique',
    alpha2: '',
    alpha3_b: 'uga',
    alpha3_t: '',
  },
  {
    english: 'Uighur; Uyghur',
    french: 'ouïgour',
    alpha2: 'ug',
    alpha3_b: 'uig',
    alpha3_t: '',
  },
  {
    english: 'Ukrainian',
    french: 'ukrainien',
    alpha2: 'uk',
    alpha3_b: 'ukr',
    alpha3_t: '',
  },
  {
    english: 'Umbundu',
    french: 'umbundu',
    alpha2: '',
    alpha3_b: 'umb',
    alpha3_t: '',
  },
  {
    english: 'Undetermined',
    french: 'indéterminée',
    alpha2: '',
    alpha3_b: 'und',
    alpha3_t: '',
  },
  {
    english: 'Urdu',
    french: 'ourdou',
    alpha2: 'ur',
    alpha3_b: 'urd',
    alpha3_t: '',
  },
  {
    english: 'Uzbek',
    french: 'ouszbek',
    alpha2: 'uz',
    alpha3_b: 'uzb',
    alpha3_t: '',
  },
  {
    english: 'Vai',
    french: 'vaï',
    alpha2: '',
    alpha3_b: 'vai',
    alpha3_t: '',
  },
  {
    english: 'Venda',
    french: 'venda',
    alpha2: 've',
    alpha3_b: 'ven',
    alpha3_t: '',
  },
  {
    english: 'Vietnamese',
    french: 'vietnamien',
    alpha2: 'vi',
    alpha3_b: 'vie',
    alpha3_t: '',
  },
  {
    english: 'Volapük',
    french: 'volapük',
    alpha2: 'vo',
    alpha3_b: 'vol',
    alpha3_t: '',
  },
  {
    english: 'Votic',
    french: 'vote',
    alpha2: '',
    alpha3_b: 'vot',
    alpha3_t: '',
  },
  {
    english: 'Wolaitta; Wolaytta',
    french: 'wolaitta; wolaytta',
    alpha2: '',
    alpha3_b: 'wal',
    alpha3_t: '',
  },
  {
    english: 'Waray',
    french: 'waray',
    alpha2: '',
    alpha3_b: 'war',
    alpha3_t: '',
  },
  {
    english: 'Washo',
    french: 'washo',
    alpha2: '',
    alpha3_b: 'was',
    alpha3_t: '',
  },
  {
    english: 'Welsh',
    french: 'gallois',
    alpha2: 'cy',
    alpha3_b: 'wel',
    alpha3_t: 'cym',
  },
  {
    english: 'Walloon',
    french: 'wallon',
    alpha2: 'wa',
    alpha3_b: 'wln',
    alpha3_t: '',
  },
  {
    english: 'Wolof',
    french: 'wolof',
    alpha2: 'wo',
    alpha3_b: 'wol',
    alpha3_t: '',
  },
  {
    english: 'Kalmyk; Oirat',
    french: 'kalmouk; oïrat',
    alpha2: '',
    alpha3_b: 'xal',
    alpha3_t: '',
  },
  {
    english: 'Xhosa',
    french: 'xhosa',
    alpha2: 'xh',
    alpha3_b: 'xho',
    alpha3_t: '',
  },
  {
    english: 'Yao',
    french: 'yao',
    alpha2: '',
    alpha3_b: 'yao',
    alpha3_t: '',
  },
  {
    english: 'Yapese',
    french: 'yapois',
    alpha2: '',
    alpha3_b: 'yap',
    alpha3_t: '',
  },
  {
    english: 'Yiddish',
    french: 'yiddish',
    alpha2: 'yi',
    alpha3_b: 'yid',
    alpha3_t: '',
  },
  {
    english: 'Yoruba',
    french: 'yoruba',
    alpha2: 'yo',
    alpha3_b: 'yor',
    alpha3_t: '',
  },
  {
    english: 'Zapotec',
    french: 'zapotèque',
    alpha2: '',
    alpha3_b: 'zap',
    alpha3_t: '',
  },
  {
    english: 'Blissymbols; Blissymbolics; Bliss',
    french: 'symboles Bliss; Bliss',
    alpha2: '',
    alpha3_b: 'zbl',
    alpha3_t: '',
  },
  {
    english: 'Zenaga',
    french: 'zenaga',
    alpha2: '',
    alpha3_b: 'zen',
    alpha3_t: '',
  },
  {
    english: 'Standard Moroccan Tamazight',
    french: 'amazighe standard marocain',
    alpha2: '',
    alpha3_b: 'zgh',
    alpha3_t: '',
  },
  {
    english: 'Zhuang; Chuang',
    french: 'zhuang; chuang',
    alpha2: 'za',
    alpha3_b: 'zha',
    alpha3_t: '',
  },
  {
    english: 'Zulu',
    french: 'zoulou',
    alpha2: 'zu',
    alpha3_b: 'zul',
    alpha3_t: '',
  },
  {
    english: 'Zuni',
    french: 'zuni',
    alpha2: '',
    alpha3_b: 'zun',
    alpha3_t: '',
  },
  {
    english: 'No linguistic content; Not applicable',
    french: 'pas de contenu linguistique; non applicable',
    alpha2: '',
    alpha3_b: 'zxx',
    alpha3_t: '',
  },
  {
    english: 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki',
    french: 'zaza; dimili; dimli; kirdki; kirmanjki; zazaki',
    alpha2: '',
    alpha3_b: 'zza',
    alpha3_t: '',
  },
];
