import type { Currency } from '../../types/currency.type';

export const currencies: Currency[] = [
  { name: 'Afghani', code: 'AFN', iso: '971' },
  { name: 'Ariary Malgache', code: 'MGA', iso: '969' },
  { name: 'Aruban Florin', code: 'AWG', iso: '533' },
  { name: 'Azerbaijanian Manat', code: 'AZN', iso: '944' },
  { name: 'Baht', code: 'THB', iso: '764' },
  { name: 'Balboa', code: 'PAB', iso: '590' },
  { name: 'Birr Éthiopienne', code: 'ETB', iso: '230' },
  { name: 'Bolivar', code: 'VEF', iso: '937' },
  { name: 'Boliviano', code: 'BOB', iso: '68' },
  { name: 'Brunei Dollar', code: 'BND', iso: '96' },
  { name: 'Cabo Verde Escudo', code: 'CVE', iso: '132' },
  { name: 'Cayman Islands Dollar', code: 'KYD', iso: '136' },
  { name: 'Cedi du Ghana', code: 'GHS', iso: '936' },
  { name: 'Cordoba', code: 'NIO', iso: '558' },
  { name: 'Costa Rican Colon', code: 'CRC', iso: '188' },
  { name: 'Couronne Danoise', code: 'DKK', iso: '208' },
  { name: 'Couronne Islandaise', code: 'ISK', iso: '352' },
  { name: 'Couronne Norvégienne', code: 'NOK', iso: '578' },
  { name: 'Couronne Suédoise', code: 'SEK', iso: '752' },
  { name: 'Couronne Tchèque', code: 'CZK', iso: '203' },
  { name: 'Dalasi', code: 'GMD', iso: '270' },
  { name: 'Denar', code: 'MKD', iso: '807' },
  { name: 'Dinar Bahraini', code: 'BHD', iso: '48' },
  { name: 'Dinar Iraquien', code: 'IQD', iso: '368' },
  { name: 'Dinar Jordanien', code: 'JOD', iso: '400' },
  { name: 'Dinar Koweïtien', code: 'KWD', iso: '414' },
  { name: 'Dinar Libien', code: 'LYD', iso: '434' },
  { name: 'Dinar Serbe', code: 'RSD', iso: '941' },
  { name: 'Dinar Tunisiens', code: 'TND', iso: '788' },
  { name: 'Dinar algériens', code: 'DZD', iso: '12' },
  { name: 'Dirham Marocain', code: 'MAD', iso: '504' },
  { name: 'Dirham UAE', code: 'AED', iso: '784' },
  { name: 'Dobra', code: 'STD', iso: '678' },
  { name: 'Dollar Australien', code: 'AUD', iso: '36' },
  { name: 'Dollar Bahaméen', code: 'BSD', iso: '44' },
  { name: 'Dollar Bermudien', code: 'BMD', iso: '60' },
  { name: 'Dollar Canadien', code: 'CAD', iso: '124' },
  { name: 'Dollar Namibien', code: 'NAD', iso: '516' },
  { name: 'Dollar Singaporien', code: 'SGD', iso: '702' },
  { name: 'Dollar US', code: 'USD', iso: '840' },
  { name: 'Dollar de Bélize', code: 'BZD', iso: '84' },
  { name: 'Dollar de Hong Kong', code: 'HKD', iso: '344' },
  { name: 'Dollar des Caraïbes orienta', code: 'XCD', iso: '951' },
  { name: 'Dollar des Fiji', code: 'FJD', iso: '242' },
  { name: 'Dollar des îles Solomon', code: 'SBD', iso: '90' },
  { name: 'Dollar du Liberia', code: 'LRD', iso: '430' },
  { name: 'Dollar guyanien', code: 'GYD', iso: '328' },
  { name: 'Dollar néo-zélandais', code: 'NZD', iso: '554' },
  { name: 'Dollars Barbados', code: 'BBD', iso: '52' },
  { name: 'Dollars Jamaïcain', code: 'JMD', iso: '388' },
  { name: 'Dollars de Trinidad et Tobago', code: 'TTD', iso: '780' },
  { name: 'Dollars du Surinam', code: 'SRD', iso: '968' },
  { name: 'Dollars du Zimbabwe', code: 'ZWL', iso: '932' },
  { name: 'Dong', code: 'VND', iso: '704' },
  { name: 'Dram Armenien', code: 'AMD', iso: '51' },
  { name: 'Euros', code: 'EUR', iso: '978' },
  { name: 'Florin des Antilles néerlandaises', code: 'ANG', iso: '532' },
  { name: 'Forint', code: 'HUF', iso: '348' },
  { name: 'Franc Burundi', code: 'BIF', iso: '108' },
  { name: 'Franc CFA (XOF)', code: 'XOF', iso: '952' },
  { name: 'Franc CFA (XAF)', code: 'XAF', iso: '950' },
  { name: 'Franc CFP', code: 'XPF', iso: '953' },
  { name: 'Franc Comorien', code: 'KMF', iso: '174' },
  { name: 'Franc Djiboutien', code: 'DJF', iso: '262' },
  { name: 'Franc Guinéen', code: 'GNF', iso: '324' },
  { name: 'Franc Rwandais', code: 'RWF', iso: '646' },
  { name: 'Franc Suisse', code: 'CHF', iso: '756' },
  { name: 'Gourde', code: 'HTG', iso: '332' },
  { name: 'Guarani', code: 'PYG', iso: '600' },
  { name: 'Hryvnia', code: 'UAH', iso: '980' },
  { name: 'Kina', code: 'PGK', iso: '598' },
  { name: 'Kip', code: 'LAK', iso: '418' },
  { name: 'Kuna', code: 'HRK', iso: '191' },
  { name: 'Kwacha', code: 'MWK', iso: '454' },
  { name: 'Kwacha Zambien', code: 'ZMW', iso: '967' },
  { name: 'Kwanza', code: 'AOA', iso: '973' },
  { name: 'Kyat', code: 'MMK', iso: '104' },
  { name: 'Lari', code: 'GEL', iso: '981' },
  { name: 'Lek', code: 'ALL', iso: '8' },
  { name: 'Lempira', code: 'HNL', iso: '340' },
  { name: 'Leone', code: 'SLL', iso: '694' },
  { name: 'Leu Moldavien', code: 'MDL', iso: '498' },
  { name: 'Leu Roumain', code: 'RON', iso: '946' },
  { name: 'Lev Bulgare', code: 'BGN', iso: '975' },
  { name: 'Lilangeni', code: 'SZL', iso: '748' },
  { name: 'Livre Soudanaise', code: 'SDG', iso: '938' },
  { name: 'Livre Sterling', code: 'GBP', iso: '826' },
  { name: 'Livre Turque', code: 'TRY', iso: '949' },
  { name: 'Livre des Îles Malouines', code: 'FKP', iso: '238' },
  { name: 'Livre sud-soudanaise', code: 'SSP', iso: '728' },
  { name: 'Manat turkmène', code: 'TMT', iso: '934' },
  { name: 'Mark Convertible', code: 'BAM', iso: '977' },
  { name: 'Mauritius Roupie', code: 'MUR', iso: '480' },
  { name: 'Metical', code: 'MZN', iso: '943' },
  { name: 'Mvdol', code: 'BOV', iso: '984' },
  { name: 'Naira', code: 'NGN', iso: '566' },
  { name: 'Nakfa', code: 'ERN', iso: '232' },
  { name: 'Ngultrum', code: 'BTN', iso: '64' },
  { name: 'Nouveau Sheqel Israélien', code: 'ILS', iso: '376' },
  { name: 'Nouveau Sol', code: 'PEN', iso: '604' },
  { name: 'Nouveau dollars Taiwanais', code: 'TWD', iso: '901' },
  { name: 'Ouguiya', code: 'MRO', iso: '478' },
  { name: 'Pataca', code: 'MOP', iso: '446' },
  { name: 'Pa’anga', code: 'TOP', iso: '776' },
  { name: 'Peso Argentin', code: 'ARS', iso: '32' },
  { name: 'Peso Chilien', code: 'CLP', iso: '152' },
  { name: 'Peso Colombien', code: 'COP', iso: '170' },
  { name: 'Peso Convertible', code: 'CUC', iso: '931' },
  { name: 'Peso Cubain', code: 'CUP', iso: '192' },
  { name: 'Peso Dominicain', code: 'DOP', iso: '214' },
  { name: 'Peso Mexicain', code: 'MXN', iso: '484' },
  { name: 'Peso Phillipins', code: 'PHP', iso: '608' },
  { name: 'Peso Uruguayen', code: 'UYU', iso: '858' },
  { name: 'Livre Libanaise', code: 'LBP', iso: '422' },
  { name: 'Livre Syrienne', code: 'SYP', iso: '760' },
  { name: 'Livre de Gibraltar', code: 'GIP', iso: '292' },
  { name: 'Livre Égyptienne', code: 'EGP', iso: '818' },
  { name: 'Pula', code: 'BWP', iso: '72' },
  { name: 'Quetzal', code: 'GTQ', iso: '320' },
  { name: 'Rand', code: 'ZAR', iso: '710' },
  { name: 'Real Brésilien', code: 'BRL', iso: '986' },
  { name: 'Rial Iranien', code: 'IRR', iso: '364' },
  { name: 'Rial Omani', code: 'OMR', iso: '512' },
  { name: 'Rial Qatari', code: 'QAR', iso: '634' },
  { name: 'Rial du Yemenl', code: 'YER', iso: '886' },
  { name: 'Riel', code: 'KHR', iso: '116' },
  { name: 'Ringgit Malaisien', code: 'MYR', iso: '458' },
  { name: 'Riyal Saoudiens', code: 'SAR', iso: '682' },
  { name: 'Rouble Russe', code: 'RUB', iso: '643' },
  { name: 'Roupie Indienne', code: 'INR', iso: '356' },
  { name: 'Roupie Indonésienne', code: 'IDR', iso: '360' },
  { name: 'Roupie Népalais', code: 'NPR', iso: '524' },
  { name: 'Roupie Sri Lankais', code: 'LKR', iso: '144' },
  { name: 'Roupie du Pakistan', code: 'PKR', iso: '586' },
  { name: 'Roupie seychelloise', code: 'SCR', iso: '690' },
  { name: 'Ruble Biélorusse', code: 'BYR', iso: '974' },
  { name: 'Rufiyaa', code: 'MVR', iso: '462' },
  { name: 'Shilling Kenyan', code: 'KES', iso: '404' },
  { name: 'Shilling Ougandaisg', code: 'UGX', iso: '800' },
  { name: 'Shilling Somalien', code: 'SOS', iso: '706' },
  { name: 'Shilling Tanzanien', code: 'TZS', iso: '834' },
  { name: 'Som', code: 'KGS', iso: '417' },
  { name: 'Somoni', code: 'TJS', iso: '972' },
  { name: 'Sum d’Oubekistan', code: 'UZS', iso: '860' },
  { name: 'Taka', code: 'BDT', iso: '50' },
  { name: 'Tala', code: 'WST', iso: '882' },
  { name: 'Tenge', code: 'KZT', iso: '398' },
  { name: 'Tugrik', code: 'MNT', iso: '496' },
  { name: 'Vatu', code: 'VUV', iso: '548' },
  { name: 'Won', code: 'KRW', iso: '410' },
  { name: 'Won Nord-coréen', code: 'KPW', iso: '408' },
  { name: 'Yen', code: 'JPY', iso: '392' },
  { name: 'Yuan Renminbi', code: 'CNY', iso: '156' },
  { name: 'Zloty', code: 'PLN', iso: '985' },
];
