import { Currency } from '../../types/currency.type';

export const currencies: Currency[] = [
  {
    alphabeticCode: 'AFN',
    currency: 'Afghani',
    entity: 'AFGHANISTAN',
    minorUnit: '2',
    numericCode: 971,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ALL',
    currency: 'Lek',
    entity: 'ALBANIA',
    minorUnit: '2',
    numericCode: 8,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'DZD',
    currency: 'Algerian Dinar',
    entity: 'ALGERIA',
    minorUnit: '2',
    numericCode: 12,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'AMERICAN SAMOA',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AOA',
    currency: 'Kwanza',
    entity: 'ANGOLA',
    minorUnit: '2',
    numericCode: 973,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XCD',
    currency: 'East Caribbean Dollar',
    entity: 'ANGUILLA',
    minorUnit: '2',
    numericCode: 951,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XCD',
    currency: 'East Caribbean Dollar',
    entity: 'ANTIGUA AND BARBUDA',
    minorUnit: '2',
    numericCode: 951,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ARS',
    currency: 'Argentine Peso',
    entity: 'ARGENTINA',
    minorUnit: '2',
    numericCode: 32,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AMD',
    currency: 'Armenian Dram',
    entity: 'ARMENIA',
    minorUnit: '2',
    numericCode: 51,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AWG',
    currency: 'Aruban Florin',
    entity: 'ARUBA',
    minorUnit: '2',
    numericCode: 533,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AUD',
    currency: 'Australian Dollar',
    entity: 'AUSTRALIA',
    minorUnit: '2',
    numericCode: 36,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AZN',
    currency: 'Azerbaijan Manat',
    entity: 'AZERBAIJAN',
    minorUnit: '2',
    numericCode: 944,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BSD',
    currency: 'Bahamian Dollar',
    entity: 'BAHAMAS (THE)',
    minorUnit: '2',
    numericCode: 44,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BHD',
    currency: 'Bahraini Dinar',
    entity: 'BAHRAIN',
    minorUnit: '3',
    numericCode: 48,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BDT',
    currency: 'Taka',
    entity: 'BANGLADESH',
    minorUnit: '2',
    numericCode: 50,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BBD',
    currency: 'Barbados Dollar',
    entity: 'BARBADOS',
    minorUnit: '2',
    numericCode: 52,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BYN',
    currency: 'Belarusian Ruble',
    entity: 'BELARUS',
    minorUnit: '2',
    numericCode: 933,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BZD',
    currency: 'Belize Dollar',
    entity: 'BELIZE',
    minorUnit: '2',
    numericCode: 84,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XOF',
    currency: 'CFA Franc BCEAO',
    entity: 'BENIN',
    minorUnit: '0',
    numericCode: 952,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BMD',
    currency: 'Bermudian Dollar',
    entity: 'BERMUDA',
    minorUnit: '2',
    numericCode: 60,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'INR',
    currency: 'Indian Rupee',
    entity: 'BHUTAN',
    minorUnit: '2',
    numericCode: 356,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BTN',
    currency: 'Ngultrum',
    entity: 'BHUTAN',
    minorUnit: '2',
    numericCode: 64,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BOB',
    currency: 'Boliviano',
    entity: 'BOLIVIA (PLURINATIONAL STATE OF)',
    minorUnit: '2',
    numericCode: 68,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BOV',
    currency: 'Mvdol',
    entity: 'BOLIVIA (PLURINATIONAL STATE OF)',
    minorUnit: '2',
    numericCode: 984,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'BONAIRE, SINT EUSTATIUS AND SABA',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BAM',
    currency: 'Convertible Mark',
    entity: 'BOSNIA AND HERZEGOVINA',
    minorUnit: '2',
    numericCode: 977,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BWP',
    currency: 'Pula',
    entity: 'BOTSWANA',
    minorUnit: '2',
    numericCode: 72,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NOK',
    currency: 'Norwegian Krone',
    entity: 'BOUVET ISLAND',
    minorUnit: '2',
    numericCode: 578,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BRL',
    currency: 'Brazilian Real',
    entity: 'BRAZIL',
    minorUnit: '2',
    numericCode: 986,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'BRITISH INDIAN OCEAN TERRITORY (THE)',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BND',
    currency: 'Brunei Dollar',
    entity: 'BRUNEI DARUSSALAM',
    minorUnit: '2',
    numericCode: 96,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BGN',
    currency: 'Bulgarian Lev',
    entity: 'BULGARIA',
    minorUnit: '2',
    numericCode: 975,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XOF',
    currency: 'CFA Franc BCEAO',
    entity: 'BURKINA FASO',
    minorUnit: '0',
    numericCode: 952,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'BIF',
    currency: 'Burundi Franc',
    entity: 'BURUNDI',
    minorUnit: '0',
    numericCode: 108,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CVE',
    currency: 'Cabo Verde Escudo',
    entity: 'CABO VERDE',
    minorUnit: '2',
    numericCode: 132,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'KHR',
    currency: 'Riel',
    entity: 'CAMBODIA',
    minorUnit: '2',
    numericCode: 116,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XAF',
    currency: 'CFA Franc BEAC',
    entity: 'CAMEROON',
    minorUnit: '0',
    numericCode: 950,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CAD',
    currency: 'Canadian Dollar',
    entity: 'CANADA',
    minorUnit: '2',
    numericCode: 124,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'KYD',
    currency: 'Cayman Islands Dollar',
    entity: 'CAYMAN ISLANDS (THE)',
    minorUnit: '2',
    numericCode: 136,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XAF',
    currency: 'CFA Franc BEAC',
    entity: 'CENTRAL AFRICAN REPUBLIC (THE)',
    minorUnit: '0',
    numericCode: 950,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XAF',
    currency: 'CFA Franc BEAC',
    entity: 'CHAD',
    minorUnit: '0',
    numericCode: 950,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CLP',
    currency: 'Chilean Peso',
    entity: 'CHILE',
    minorUnit: '0',
    numericCode: 152,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CLF',
    currency: 'Unidad de Fomento',
    entity: 'CHILE',
    minorUnit: '4',
    numericCode: 990,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CNY',
    currency: 'Yuan Renminbi',
    entity: 'CHINA',
    minorUnit: '2',
    numericCode: 156,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AUD',
    currency: 'Australian Dollar',
    entity: 'CHRISTMAS ISLAND',
    minorUnit: '2',
    numericCode: 36,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AUD',
    currency: 'Australian Dollar',
    entity: 'COCOS (KEELING) ISLANDS (THE)',
    minorUnit: '2',
    numericCode: 36,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'COP',
    currency: 'Colombian Peso',
    entity: 'COLOMBIA',
    minorUnit: '2',
    numericCode: 170,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'COU',
    currency: 'Unidad de Valor Real',
    entity: 'COLOMBIA',
    minorUnit: '2',
    numericCode: 970,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'KMF',
    currency: 'Comorian Franc',
    entity: 'COMOROS (THE)',
    minorUnit: '0',
    numericCode: 174,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CDF',
    currency: 'Congolese Franc',
    entity: 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
    minorUnit: '2',
    numericCode: 976,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XAF',
    currency: 'CFA Franc BEAC',
    entity: 'CONGO (THE)',
    minorUnit: '0',
    numericCode: 950,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NZD',
    currency: 'New Zealand Dollar',
    entity: 'COOK ISLANDS (THE)',
    minorUnit: '2',
    numericCode: 554,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CRC',
    currency: 'Costa Rican Colon',
    entity: 'COSTA RICA',
    minorUnit: '2',
    numericCode: 188,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XOF',
    currency: 'CFA Franc BCEAO',
    entity: "CÔTE D'IVOIRE",
    minorUnit: '0',
    numericCode: 952,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'HRK',
    currency: 'Kuna',
    entity: 'CROATIA',
    minorUnit: '2',
    numericCode: 191,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CUP',
    currency: 'Cuban Peso',
    entity: 'CUBA',
    minorUnit: '2',
    numericCode: 192,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CUC',
    currency: 'Peso Convertible',
    entity: 'CUBA',
    minorUnit: '2',
    numericCode: 931,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ANG',
    currency: 'Netherlands Antillean Guilder',
    entity: 'CURAÇAO',
    minorUnit: '2',
    numericCode: 532,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CZK',
    currency: 'Czech Koruna',
    entity: 'CZECHIA',
    minorUnit: '2',
    numericCode: 203,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'DKK',
    currency: 'Danish Krone',
    entity: 'DENMARK',
    minorUnit: '2',
    numericCode: 208,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'DJF',
    currency: 'Djibouti Franc',
    entity: 'DJIBOUTI',
    minorUnit: '0',
    numericCode: 262,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XCD',
    currency: 'East Caribbean Dollar',
    entity: 'DOMINICA',
    minorUnit: '2',
    numericCode: 951,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'DOP',
    currency: 'Dominican Peso',
    entity: 'DOMINICAN REPUBLIC (THE)',
    minorUnit: '2',
    numericCode: 214,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'ECUADOR',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EGP',
    currency: 'Egyptian Pound',
    entity: 'EGYPT',
    minorUnit: '2',
    numericCode: 818,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SVC',
    currency: 'El Salvador Colon',
    entity: 'EL SALVADOR',
    minorUnit: '2',
    numericCode: 222,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'EL SALVADOR',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XAF',
    currency: 'CFA Franc BEAC',
    entity: 'EQUATORIAL GUINEA',
    minorUnit: '0',
    numericCode: 950,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ERN',
    currency: 'Nakfa',
    entity: 'ERITREA',
    minorUnit: '2',
    numericCode: 232,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SZL',
    currency: 'Lilangeni',
    entity: 'ESWATINI',
    minorUnit: '2',
    numericCode: 748,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ETB',
    currency: 'Ethiopian Birr',
    entity: 'ETHIOPIA',
    minorUnit: '2',
    numericCode: 230,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'EUROPEAN UNION',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'FKP',
    currency: 'Falkland Islands Pound',
    entity: 'FALKLAND ISLANDS (THE) [MALVINAS]',
    minorUnit: '2',
    numericCode: 238,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'DKK',
    currency: 'Danish Krone',
    entity: 'FAROE ISLANDS (THE)',
    minorUnit: '2',
    numericCode: 208,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'FJD',
    currency: 'Fiji Dollar',
    entity: 'FIJI',
    minorUnit: '2',
    numericCode: 242,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XPF',
    currency: 'CFP Franc',
    entity: 'FRENCH POLYNESIA',
    minorUnit: '0',
    numericCode: 953,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XAF',
    currency: 'CFA Franc BEAC',
    entity: 'GABON',
    minorUnit: '0',
    numericCode: 950,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'GMD',
    currency: 'Dalasi',
    entity: 'GAMBIA (THE)',
    minorUnit: '2',
    numericCode: 270,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'GEL',
    currency: 'Lari',
    entity: 'GEORGIA',
    minorUnit: '2',
    numericCode: 981,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'GHS',
    currency: 'Ghana Cedi',
    entity: 'GHANA',
    minorUnit: '2',
    numericCode: 936,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'GIP',
    currency: 'Gibraltar Pound',
    entity: 'GIBRALTAR',
    minorUnit: '2',
    numericCode: 292,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'DKK',
    currency: 'Danish Krone',
    entity: 'GREENLAND',
    minorUnit: '2',
    numericCode: 208,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XCD',
    currency: 'East Caribbean Dollar',
    entity: 'GRENADA',
    minorUnit: '2',
    numericCode: 951,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'GUAM',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'GTQ',
    currency: 'Quetzal',
    entity: 'GUATEMALA',
    minorUnit: '2',
    numericCode: 320,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'GBP',
    currency: 'Pound Sterling',
    entity: 'GUERNSEY',
    minorUnit: '2',
    numericCode: 826,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'GNF',
    currency: 'Guinean Franc',
    entity: 'GUINEA',
    minorUnit: '0',
    numericCode: 324,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XOF',
    currency: 'CFA Franc BCEAO',
    entity: 'GUINEA-BISSAU',
    minorUnit: '0',
    numericCode: 952,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'GYD',
    currency: 'Guyana Dollar',
    entity: 'GUYANA',
    minorUnit: '2',
    numericCode: 328,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'HTG',
    currency: 'Gourde',
    entity: 'HAITI',
    minorUnit: '2',
    numericCode: 332,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'HAITI',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AUD',
    currency: 'Australian Dollar',
    entity: 'HEARD ISLAND AND McDONALD ISLANDS',
    minorUnit: '2',
    numericCode: 36,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'HNL',
    currency: 'Lempira',
    entity: 'HONDURAS',
    minorUnit: '2',
    numericCode: 340,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'HKD',
    currency: 'Hong Kong Dollar',
    entity: 'HONG KONG',
    minorUnit: '2',
    numericCode: 344,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'HUF',
    currency: 'Forint',
    entity: 'HUNGARY',
    minorUnit: '2',
    numericCode: 348,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ISK',
    currency: 'Iceland Krona',
    entity: 'ICELAND',
    minorUnit: '0',
    numericCode: 352,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'INR',
    currency: 'Indian Rupee',
    entity: 'INDIA',
    minorUnit: '2',
    numericCode: 356,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'IDR',
    currency: 'Rupiah',
    entity: 'INDONESIA',
    minorUnit: '2',
    numericCode: 360,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XDR',
    currency: 'SDR (Special Drawing Right)',
    entity: 'INTERNATIONAL MONETARY FUND (IMF)',
    minorUnit: '-',
    numericCode: 960,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'IRR',
    currency: 'Iranian Rial',
    entity: 'IRAN (ISLAMIC REPUBLIC OF)',
    minorUnit: '2',
    numericCode: 364,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'IQD',
    currency: 'Iraqi Dinar',
    entity: 'IRAQ',
    minorUnit: '3',
    numericCode: 368,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'GBP',
    currency: 'Pound Sterling',
    entity: 'ISLE OF MAN',
    minorUnit: '2',
    numericCode: 826,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ILS',
    currency: 'New Israeli Sheqel',
    entity: 'ISRAEL',
    minorUnit: '2',
    numericCode: 376,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'JMD',
    currency: 'Jamaican Dollar',
    entity: 'JAMAICA',
    minorUnit: '2',
    numericCode: 388,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'JPY',
    currency: 'Yen',
    entity: 'JAPAN',
    minorUnit: '0',
    numericCode: 392,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'GBP',
    currency: 'Pound Sterling',
    entity: 'JERSEY',
    minorUnit: '2',
    numericCode: 826,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'JOD',
    currency: 'Jordanian Dinar',
    entity: 'JORDAN',
    minorUnit: '3',
    numericCode: 400,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'KZT',
    currency: 'Tenge',
    entity: 'KAZAKHSTAN',
    minorUnit: '2',
    numericCode: 398,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'KES',
    currency: 'Kenyan Shilling',
    entity: 'KENYA',
    minorUnit: '2',
    numericCode: 404,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AUD',
    currency: 'Australian Dollar',
    entity: 'KIRIBATI',
    minorUnit: '2',
    numericCode: 36,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'KPW',
    currency: 'North Korean Won',
    entity: "KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)",
    minorUnit: '2',
    numericCode: 408,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'KRW',
    currency: 'Won',
    entity: 'KOREA (THE REPUBLIC OF)',
    minorUnit: '0',
    numericCode: 410,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'KWD',
    currency: 'Kuwaiti Dinar',
    entity: 'KUWAIT',
    minorUnit: '3',
    numericCode: 414,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'KGS',
    currency: 'Som',
    entity: 'KYRGYZSTAN',
    minorUnit: '2',
    numericCode: 417,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'LAK',
    currency: 'Lao Kip',
    entity: "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
    minorUnit: '2',
    numericCode: 418,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'LBP',
    currency: 'Lebanese Pound',
    entity: 'LEBANON',
    minorUnit: '2',
    numericCode: 422,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'LSL',
    currency: 'Loti',
    entity: 'LESOTHO',
    minorUnit: '2',
    numericCode: 426,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ZAR',
    currency: 'Rand',
    entity: 'LESOTHO',
    minorUnit: '2',
    numericCode: 710,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'LRD',
    currency: 'Liberian Dollar',
    entity: 'LIBERIA',
    minorUnit: '2',
    numericCode: 430,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'LYD',
    currency: 'Libyan Dinar',
    entity: 'LIBYA',
    minorUnit: '3',
    numericCode: 434,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CHF',
    currency: 'Swiss Franc',
    entity: 'LIECHTENSTEIN',
    minorUnit: '2',
    numericCode: 756,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MOP',
    currency: 'Pataca',
    entity: 'MACAO',
    minorUnit: '2',
    numericCode: 446,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MKD',
    currency: 'Denar',
    entity: 'NORTH MACEDONIA',
    minorUnit: '2',
    numericCode: 807,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MGA',
    currency: 'Malagasy Ariary',
    entity: 'MADAGASCAR',
    minorUnit: '2',
    numericCode: 969,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MWK',
    currency: 'Malawi Kwacha',
    entity: 'MALAWI',
    minorUnit: '2',
    numericCode: 454,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MYR',
    currency: 'Malaysian Ringgit',
    entity: 'MALAYSIA',
    minorUnit: '2',
    numericCode: 458,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MVR',
    currency: 'Rufiyaa',
    entity: 'MALDIVES',
    minorUnit: '2',
    numericCode: 462,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XOF',
    currency: 'CFA Franc BCEAO',
    entity: 'MALI',
    minorUnit: '0',
    numericCode: 952,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'MARSHALL ISLANDS (THE)',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MRU',
    currency: 'Ouguiya',
    entity: 'MAURITANIA',
    minorUnit: '2',
    numericCode: 929,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MUR',
    currency: 'Mauritius Rupee',
    entity: 'MAURITIUS',
    minorUnit: '2',
    numericCode: 480,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XUA',
    currency: 'ADB Unit of Account',
    entity: 'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP',
    minorUnit: '-',
    numericCode: 965,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MXN',
    currency: 'Mexican Peso',
    entity: 'MEXICO',
    minorUnit: '2',
    numericCode: 484,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MXV',
    currency: 'Mexican Unidad de Inversion (UDI)',
    entity: 'MEXICO',
    minorUnit: '2',
    numericCode: 979,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'MICRONESIA (FEDERATED STATES OF)',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MDL',
    currency: 'Moldovan Leu',
    entity: 'MOLDOVA (THE REPUBLIC OF)',
    minorUnit: '2',
    numericCode: 498,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'MONACO',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MNT',
    currency: 'Tugrik',
    entity: 'MONGOLIA',
    minorUnit: '2',
    numericCode: 496,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'MONTENEGRO',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XCD',
    currency: 'East Caribbean Dollar',
    entity: 'MONTSERRAT',
    minorUnit: '2',
    numericCode: 951,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MAD',
    currency: 'Moroccan Dirham',
    entity: 'MOROCCO',
    minorUnit: '2',
    numericCode: 504,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MZN',
    currency: 'Mozambique Metical',
    entity: 'MOZAMBIQUE',
    minorUnit: '2',
    numericCode: 943,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MMK',
    currency: 'Kyat',
    entity: 'MYANMAR',
    minorUnit: '2',
    numericCode: 104,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NAD',
    currency: 'Namibia Dollar',
    entity: 'NAMIBIA',
    minorUnit: '2',
    numericCode: 516,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ZAR',
    currency: 'Rand',
    entity: 'NAMIBIA',
    minorUnit: '2',
    numericCode: 710,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AUD',
    currency: 'Australian Dollar',
    entity: 'NAURU',
    minorUnit: '2',
    numericCode: 36,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NPR',
    currency: 'Nepalese Rupee',
    entity: 'NEPAL',
    minorUnit: '2',
    numericCode: 524,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'NETHERLANDS (THE)',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XPF',
    currency: 'CFP Franc',
    entity: 'NEW CALEDONIA',
    minorUnit: '0',
    numericCode: 953,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NZD',
    currency: 'New Zealand Dollar',
    entity: 'NEW ZEALAND',
    minorUnit: '2',
    numericCode: 554,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NIO',
    currency: 'Cordoba Oro',
    entity: 'NICARAGUA',
    minorUnit: '2',
    numericCode: 558,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XOF',
    currency: 'CFA Franc BCEAO',
    entity: 'NIGER (THE)',
    minorUnit: '0',
    numericCode: 952,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NGN',
    currency: 'Naira',
    entity: 'NIGERIA',
    minorUnit: '2',
    numericCode: 566,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NZD',
    currency: 'New Zealand Dollar',
    entity: 'NIUE',
    minorUnit: '2',
    numericCode: 554,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AUD',
    currency: 'Australian Dollar',
    entity: 'NORFOLK ISLAND',
    minorUnit: '2',
    numericCode: 36,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'NORTHERN MARIANA ISLANDS (THE)',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NOK',
    currency: 'Norwegian Krone',
    entity: 'NORWAY',
    minorUnit: '2',
    numericCode: 578,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'OMR',
    currency: 'Rial Omani',
    entity: 'OMAN',
    minorUnit: '3',
    numericCode: 512,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'PKR',
    currency: 'Pakistan Rupee',
    entity: 'PAKISTAN',
    minorUnit: '2',
    numericCode: 586,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'PALAU',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'PAB',
    currency: 'Balboa',
    entity: 'PANAMA',
    minorUnit: '2',
    numericCode: 590,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'PANAMA',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'PGK',
    currency: 'Kina',
    entity: 'PAPUA NEW GUINEA',
    minorUnit: '2',
    numericCode: 598,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'PYG',
    currency: 'Guarani',
    entity: 'PARAGUAY',
    minorUnit: '0',
    numericCode: 600,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'PEN',
    currency: 'Sol',
    entity: 'PERU',
    minorUnit: '2',
    numericCode: 604,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'PHP',
    currency: 'Philippine Peso',
    entity: 'PHILIPPINES (THE)',
    minorUnit: '2',
    numericCode: 608,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NZD',
    currency: 'New Zealand Dollar',
    entity: 'PITCAIRN',
    minorUnit: '2',
    numericCode: 554,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'PLN',
    currency: 'Zloty',
    entity: 'POLAND',
    minorUnit: '2',
    numericCode: 985,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'PORTUGAL',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'PUERTO RICO',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'QAR',
    currency: 'Qatari Rial',
    entity: 'QATAR',
    minorUnit: '2',
    numericCode: 634,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'RÉUNION',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'RON',
    currency: 'Romanian Leu',
    entity: 'ROMANIA',
    minorUnit: '2',
    numericCode: 946,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'RUB',
    currency: 'Russian Ruble',
    entity: 'RUSSIAN FEDERATION (THE)',
    minorUnit: '2',
    numericCode: 643,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'RWF',
    currency: 'Rwanda Franc',
    entity: 'RWANDA',
    minorUnit: '0',
    numericCode: 646,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'SAINT BARTHÉLEMY',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SHP',
    currency: 'Saint Helena Pound',
    entity: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
    minorUnit: '2',
    numericCode: 654,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XCD',
    currency: 'East Caribbean Dollar',
    entity: 'SAINT KITTS AND NEVIS',
    minorUnit: '2',
    numericCode: 951,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XCD',
    currency: 'East Caribbean Dollar',
    entity: 'SAINT LUCIA',
    minorUnit: '2',
    numericCode: 951,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'SAINT MARTIN (FRENCH PART)',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'SAINT PIERRE AND MIQUELON',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XCD',
    currency: 'East Caribbean Dollar',
    entity: 'SAINT VINCENT AND THE GRENADINES',
    minorUnit: '2',
    numericCode: 951,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'WST',
    currency: 'Tala',
    entity: 'SAMOA',
    minorUnit: '2',
    numericCode: 882,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'SAN MARINO',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'STN',
    currency: 'Dobra',
    entity: 'SAO TOME AND PRINCIPE',
    minorUnit: '2',
    numericCode: 930,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SAR',
    currency: 'Saudi Riyal',
    entity: 'SAUDI ARABIA',
    minorUnit: '2',
    numericCode: 682,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XOF',
    currency: 'CFA Franc BCEAO',
    entity: 'SENEGAL',
    minorUnit: '0',
    numericCode: 952,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'RSD',
    currency: 'Serbian Dinar',
    entity: 'SERBIA',
    minorUnit: '2',
    numericCode: 941,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SCR',
    currency: 'Seychelles Rupee',
    entity: 'SEYCHELLES',
    minorUnit: '2',
    numericCode: 690,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SLL',
    currency: 'Leone',
    entity: 'SIERRA LEONE',
    minorUnit: '2',
    numericCode: 694,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SGD',
    currency: 'Singapore Dollar',
    entity: 'SINGAPORE',
    minorUnit: '2',
    numericCode: 702,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ANG',
    currency: 'Netherlands Antillean Guilder',
    entity: 'SINT MAARTEN (DUTCH PART)',
    minorUnit: '2',
    numericCode: 532,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XSU',
    currency: 'Sucre',
    entity: 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"',
    minorUnit: '-',
    numericCode: 994,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'SLOVAKIA',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'SLOVENIA',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SBD',
    currency: 'Solomon Islands Dollar',
    entity: 'SOLOMON ISLANDS',
    minorUnit: '2',
    numericCode: 90,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SOS',
    currency: 'Somali Shilling',
    entity: 'SOMALIA',
    minorUnit: '2',
    numericCode: 706,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ZAR',
    currency: 'Rand',
    entity: 'SOUTH AFRICA',
    minorUnit: '2',
    numericCode: 710,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SSP',
    currency: 'South Sudanese Pound',
    entity: 'SOUTH SUDAN',
    minorUnit: '2',
    numericCode: 728,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'SPAIN',
    minorUnit: '2',
    numericCode: 978,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'LKR',
    currency: 'Sri Lanka Rupee',
    entity: 'SRI LANKA',
    minorUnit: '2',
    numericCode: 144,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SDG',
    currency: 'Sudanese Pound',
    entity: 'SUDAN (THE)',
    minorUnit: '2',
    numericCode: 938,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SRD',
    currency: 'Surinam Dollar',
    entity: 'SURINAME',
    minorUnit: '2',
    numericCode: 968,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NOK',
    currency: 'Norwegian Krone',
    entity: 'SVALBARD AND JAN MAYEN',
    minorUnit: '2',
    numericCode: 578,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SEK',
    currency: 'Swedish Krona',
    entity: 'SWEDEN',
    minorUnit: '2',
    numericCode: 752,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CHF',
    currency: 'Swiss Franc',
    entity: 'SWITZERLAND',
    minorUnit: '2',
    numericCode: 756,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CHE',
    currency: 'WIR Euro',
    entity: 'SWITZERLAND',
    minorUnit: '2',
    numericCode: 947,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'CHW',
    currency: 'WIR Franc',
    entity: 'SWITZERLAND',
    minorUnit: '2',
    numericCode: 948,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'SYP',
    currency: 'Syrian Pound',
    entity: 'SYRIAN ARAB REPUBLIC',
    minorUnit: '2',
    numericCode: 760,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'TWD',
    currency: 'New Taiwan Dollar',
    entity: 'TAIWAN (PROVINCE OF CHINA)',
    minorUnit: '2',
    numericCode: 901,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'TJS',
    currency: 'Somoni',
    entity: 'TAJIKISTAN',
    minorUnit: '2',
    numericCode: 972,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'TZS',
    currency: 'Tanzanian Shilling',
    entity: 'TANZANIA, UNITED REPUBLIC OF',
    minorUnit: '2',
    numericCode: 834,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'THB',
    currency: 'Baht',
    entity: 'THAILAND',
    minorUnit: '2',
    numericCode: 764,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'TIMOR-LESTE',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XOF',
    currency: 'CFA Franc BCEAO',
    entity: 'TOGO',
    minorUnit: '0',
    numericCode: 952,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'NZD',
    currency: 'New Zealand Dollar',
    entity: 'TOKELAU',
    minorUnit: '2',
    numericCode: 554,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'TOP',
    currency: "Pa'anga",
    entity: 'TONGA',
    minorUnit: '2',
    numericCode: 776,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'TTD',
    currency: 'Trinidad and Tobago Dollar',
    entity: 'TRINIDAD AND TOBAGO',
    minorUnit: '2',
    numericCode: 780,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'TND',
    currency: 'Tunisian Dinar',
    entity: 'TUNISIA',
    minorUnit: '3',
    numericCode: 788,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'TRY',
    currency: 'Turkish Lira',
    entity: 'TURKEY',
    minorUnit: '2',
    numericCode: 949,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'TMT',
    currency: 'Turkmenistan New Manat',
    entity: 'TURKMENISTAN',
    minorUnit: '2',
    numericCode: 934,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'TURKS AND CAICOS ISLANDS (THE)',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AUD',
    currency: 'Australian Dollar',
    entity: 'TUVALU',
    minorUnit: '2',
    numericCode: 36,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'UGX',
    currency: 'Uganda Shilling',
    entity: 'UGANDA',
    minorUnit: '0',
    numericCode: 800,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'UAH',
    currency: 'Hryvnia',
    entity: 'UKRAINE',
    minorUnit: '2',
    numericCode: 980,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AED',
    currency: 'UAE Dirham',
    entity: 'UNITED ARAB EMIRATES (THE)',
    minorUnit: '2',
    numericCode: 784,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'GBP',
    currency: 'Pound Sterling',
    entity: 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
    minorUnit: '2',
    numericCode: 826,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'UNITED STATES MINOR OUTLYING ISLANDS (THE)',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'UNITED STATES OF AMERICA (THE)',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USN',
    currency: 'US Dollar (Next day)',
    entity: 'UNITED STATES OF AMERICA (THE)',
    minorUnit: '2',
    numericCode: 997,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'UYU',
    currency: 'Peso Uruguayo',
    entity: 'URUGUAY',
    minorUnit: '2',
    numericCode: 858,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'UYI',
    currency: 'Uruguay Peso en Unidades Indexadas (UI)',
    entity: 'URUGUAY',
    minorUnit: '0',
    numericCode: 940,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'UYW',
    currency: 'Unidad Previsional',
    entity: 'URUGUAY',
    minorUnit: '4',
    numericCode: 927,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'UZS',
    currency: 'Uzbekistan Sum',
    entity: 'UZBEKISTAN',
    minorUnit: '2',
    numericCode: 860,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'VUV',
    currency: 'Vatu',
    entity: 'VANUATU',
    minorUnit: '0',
    numericCode: 548,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'VES',
    currency: 'Bolívar Soberano',
    entity: 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
    minorUnit: '2',
    numericCode: 928,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'VND',
    currency: 'Dong',
    entity: 'VIET NAM',
    minorUnit: '0',
    numericCode: 704,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'VIRGIN ISLANDS (BRITISH)',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'USD',
    currency: 'US Dollar',
    entity: 'VIRGIN ISLANDS (U.S.)',
    minorUnit: '2',
    numericCode: 840,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XPF',
    currency: 'CFP Franc',
    entity: 'WALLIS AND FUTUNA',
    minorUnit: '0',
    numericCode: 953,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'MAD',
    currency: 'Moroccan Dirham',
    entity: 'WESTERN SAHARA',
    minorUnit: '2',
    numericCode: 504,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'YER',
    currency: 'Yemeni Rial',
    entity: 'YEMEN',
    minorUnit: '2',
    numericCode: 886,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ZMW',
    currency: 'Zambian Kwacha',
    entity: 'ZAMBIA',
    minorUnit: '2',
    numericCode: 967,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'ZWL',
    currency: 'Zimbabwe Dollar',
    entity: 'ZIMBABWE',
    minorUnit: '2',
    numericCode: 932,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XBA',
    currency: 'Bond Markets Unit European Composite Unit (EURCO)',
    entity: 'ZZ01_Bond Markets Unit European_EURCO',
    minorUnit: '-',
    numericCode: 955,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XBB',
    currency: 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
    entity: 'ZZ02_Bond Markets Unit European_EMU-6',
    minorUnit: '-',
    numericCode: 956,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XBC',
    currency: 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
    entity: 'ZZ03_Bond Markets Unit European_EUA-9',
    minorUnit: '-',
    numericCode: 957,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XBD',
    currency: 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
    entity: 'ZZ04_Bond Markets Unit European_EUA-17',
    minorUnit: '-',
    numericCode: 958,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XTS',
    currency: 'Codes specifically reserved for testing purposes',
    entity: 'ZZ06_Testing_Code',
    minorUnit: '-',
    numericCode: 963,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XXX',
    currency: 'The codes assigned for transactions where no currency is involved',
    entity: 'ZZ07_No_currency',
    minorUnit: '-',
    numericCode: 999,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XAU',
    currency: 'Gold',
    entity: 'ZZ08_Gold',
    minorUnit: '-',
    numericCode: 959,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XPD',
    currency: 'Palladium',
    entity: 'ZZ09_Palladium',
    minorUnit: '-',
    numericCode: 964,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XPT',
    currency: 'Platinum',
    entity: 'ZZ10_Platinum',
    minorUnit: '-',
    numericCode: 962,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'XAG',
    currency: 'Silver',
    entity: 'ZZ11_Silver',
    minorUnit: '-',
    numericCode: 961,
    withdrawalDate: '',
  },
  {
    alphabeticCode: 'AFA',
    currency: 'Afghani',
    entity: 'AFGHANISTAN',
    minorUnit: '',
    numericCode: 4,
    withdrawalDate: '2003-01',
  },
  {
    alphabeticCode: 'FIM',
    currency: 'Markka',
    entity: 'ÅLAND ISLANDS',
    minorUnit: '',
    numericCode: 246,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'ALK',
    currency: 'Old Lek',
    entity: 'ALBANIA',
    minorUnit: '',
    numericCode: 8,
    withdrawalDate: '1989-12',
  },
  {
    alphabeticCode: 'ADP',
    currency: 'Andorran Peseta',
    entity: 'ANDORRA',
    minorUnit: '',
    numericCode: 20,
    withdrawalDate: '2003-07',
  },
  {
    alphabeticCode: 'ESP',
    currency: 'Spanish Peseta',
    entity: 'ANDORRA',
    minorUnit: '',
    numericCode: 724,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'ANDORRA',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'AOK',
    currency: 'Kwanza',
    entity: 'ANGOLA',
    minorUnit: '',
    numericCode: 24,
    withdrawalDate: '1991-03',
  },
  {
    alphabeticCode: 'AON',
    currency: 'New Kwanza',
    entity: 'ANGOLA',
    minorUnit: '',
    numericCode: 24,
    withdrawalDate: '2000-02',
  },
  {
    alphabeticCode: 'AOR',
    currency: 'Kwanza Reajustado',
    entity: 'ANGOLA',
    minorUnit: '',
    numericCode: 982,
    withdrawalDate: '2000-02',
  },
  {
    alphabeticCode: 'ARA',
    currency: 'Austral',
    entity: 'ARGENTINA',
    minorUnit: '',
    numericCode: 32,
    withdrawalDate: '1992-01',
  },
  {
    alphabeticCode: 'ARP',
    currency: 'Peso Argentino',
    entity: 'ARGENTINA',
    minorUnit: '',
    numericCode: 32,
    withdrawalDate: '1985-07',
  },
  {
    alphabeticCode: 'ARY',
    currency: 'Peso',
    entity: 'ARGENTINA',
    minorUnit: '',
    numericCode: 32,
    withdrawalDate: '1989 to 1990',
  },
  {
    alphabeticCode: 'RUR',
    currency: 'Russian Ruble',
    entity: 'ARMENIA',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '1994-08',
  },
  {
    alphabeticCode: 'ATS',
    currency: 'Schilling',
    entity: 'AUSTRIA',
    minorUnit: '',
    numericCode: 40,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'AYM',
    currency: 'Azerbaijan Manat',
    entity: 'AZERBAIJAN',
    minorUnit: '',
    numericCode: 945,
    withdrawalDate: '2005-10',
  },
  {
    alphabeticCode: 'AZM',
    currency: 'Azerbaijanian Manat',
    entity: 'AZERBAIJAN',
    minorUnit: '',
    numericCode: 31,
    withdrawalDate: '2005-12',
  },
  {
    alphabeticCode: 'RUR',
    currency: 'Russian Ruble',
    entity: 'AZERBAIJAN',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '1994-08',
  },
  {
    alphabeticCode: 'BYB',
    currency: 'Belarusian Ruble',
    entity: 'BELARUS',
    minorUnit: '',
    numericCode: 112,
    withdrawalDate: '2001-01',
  },
  {
    alphabeticCode: 'BYR',
    currency: 'Belarusian Ruble',
    entity: 'BELARUS',
    minorUnit: '',
    numericCode: 974,
    withdrawalDate: '2017-01',
  },
  {
    alphabeticCode: 'RUR',
    currency: 'Russian Ruble',
    entity: 'BELARUS',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '1994-06',
  },
  {
    alphabeticCode: 'BEC',
    currency: 'Convertible Franc',
    entity: 'BELGIUM',
    minorUnit: '',
    numericCode: 993,
    withdrawalDate: '1990-03',
  },
  {
    alphabeticCode: 'BEF',
    currency: 'Belgian Franc',
    entity: 'BELGIUM',
    minorUnit: '',
    numericCode: 56,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'BEL',
    currency: 'Financial Franc',
    entity: 'BELGIUM',
    minorUnit: '',
    numericCode: 992,
    withdrawalDate: '1990-03',
  },
  {
    alphabeticCode: 'BOP',
    currency: 'Peso boliviano',
    entity: 'BOLIVIA',
    minorUnit: '',
    numericCode: 68,
    withdrawalDate: '1987-02',
  },
  {
    alphabeticCode: 'BAD',
    currency: 'Dinar',
    entity: 'BOSNIA AND HERZEGOVINA',
    minorUnit: '',
    numericCode: 70,
    withdrawalDate: '1998-07',
  },
  {
    alphabeticCode: 'BRB',
    currency: 'Cruzeiro',
    entity: 'BRAZIL',
    minorUnit: '',
    numericCode: 76,
    withdrawalDate: '1986-03',
  },
  {
    alphabeticCode: 'BRC',
    currency: 'Cruzado',
    entity: 'BRAZIL',
    minorUnit: '',
    numericCode: 76,
    withdrawalDate: '1989-02',
  },
  {
    alphabeticCode: 'BRE',
    currency: 'Cruzeiro',
    entity: 'BRAZIL',
    minorUnit: '',
    numericCode: 76,
    withdrawalDate: '1993-03',
  },
  {
    alphabeticCode: 'BRN',
    currency: 'New Cruzado',
    entity: 'BRAZIL',
    minorUnit: '',
    numericCode: 76,
    withdrawalDate: '1990-03',
  },
  {
    alphabeticCode: 'BRR',
    currency: 'Cruzeiro Real',
    entity: 'BRAZIL',
    minorUnit: '',
    numericCode: 987,
    withdrawalDate: '1994-07',
  },
  {
    alphabeticCode: 'BGJ',
    currency: 'Lev A/52',
    entity: 'BULGARIA',
    minorUnit: '',
    numericCode: 100,
    withdrawalDate: '1989 to 1990',
  },
  {
    alphabeticCode: 'BGK',
    currency: 'Lev A/62',
    entity: 'BULGARIA',
    minorUnit: '',
    numericCode: 100,
    withdrawalDate: '1989 to 1990',
  },
  {
    alphabeticCode: 'BGL',
    currency: 'Lev',
    entity: 'BULGARIA',
    minorUnit: '',
    numericCode: 100,
    withdrawalDate: '2003-11',
  },
  {
    alphabeticCode: 'BUK',
    currency: 'Kyat',
    entity: 'BURMA',
    minorUnit: '',
    numericCode: 104,
    withdrawalDate: '1990-02',
  },
  {
    alphabeticCode: 'HRD',
    currency: 'Croatian Dinar',
    entity: 'CROATIA',
    minorUnit: '',
    numericCode: 191,
    withdrawalDate: '1995-01',
  },
  {
    alphabeticCode: 'HRK',
    currency: 'Croatian Kuna',
    entity: 'CROATIA',
    minorUnit: '',
    numericCode: 191,
    withdrawalDate: '2015-06',
  },
  {
    alphabeticCode: 'CYP',
    currency: 'Cyprus Pound',
    entity: 'CYPRUS',
    minorUnit: '',
    numericCode: 196,
    withdrawalDate: '2008-01',
  },
  {
    alphabeticCode: 'CSJ',
    currency: 'Krona A/53',
    entity: 'CZECHOSLOVAKIA',
    minorUnit: '',
    numericCode: 203,
    withdrawalDate: '1989 to 1990',
  },
  {
    alphabeticCode: 'CSK',
    currency: 'Koruna',
    entity: 'CZECHOSLOVAKIA',
    minorUnit: '',
    numericCode: 200,
    withdrawalDate: '1993-03',
  },
  {
    alphabeticCode: 'ECS',
    currency: 'Sucre',
    entity: 'ECUADOR',
    minorUnit: '',
    numericCode: 218,
    withdrawalDate: '2000-09',
  },
  {
    alphabeticCode: 'ECV',
    currency: 'Unidad de Valor Constante (UVC)',
    entity: 'ECUADOR',
    minorUnit: '',
    numericCode: 983,
    withdrawalDate: '2000-09',
  },
  {
    alphabeticCode: 'GQE',
    currency: 'Ekwele',
    entity: 'EQUATORIAL GUINEA',
    minorUnit: '',
    numericCode: 226,
    withdrawalDate: '1986-06',
  },
  {
    alphabeticCode: 'EEK',
    currency: 'Kroon',
    entity: 'ESTONIA',
    minorUnit: '',
    numericCode: 233,
    withdrawalDate: '2011-01',
  },
  {
    alphabeticCode: 'XEU',
    currency: 'European currency Unit (E.C.U)',
    entity: 'EUROPEAN MONETARY CO-OPERATION FUND (EMCF)',
    minorUnit: '',
    numericCode: 954,
    withdrawalDate: '1999-01',
  },
  {
    alphabeticCode: 'FIM',
    currency: 'Markka',
    entity: 'FINLAND',
    minorUnit: '',
    numericCode: 246,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'FRANCE',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'FRENCH GUIANA',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'FRENCH SOUTHERN TERRITORIES',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'GEK',
    currency: 'Georgian Coupon',
    entity: 'GEORGIA',
    minorUnit: '',
    numericCode: 268,
    withdrawalDate: '1995-10',
  },
  {
    alphabeticCode: 'RUR',
    currency: 'Russian Ruble',
    entity: 'GEORGIA',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '1994-04',
  },
  {
    alphabeticCode: 'DDM',
    currency: 'Mark der DDR',
    entity: 'GERMAN DEMOCRATIC REPUBLIC',
    minorUnit: '',
    numericCode: 278,
    withdrawalDate: '1990-07 to 1990-09',
  },
  {
    alphabeticCode: 'DEM',
    currency: 'Deutsche Mark',
    entity: 'GERMANY',
    minorUnit: '',
    numericCode: 276,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'GHC',
    currency: 'Cedi',
    entity: 'GHANA',
    minorUnit: '',
    numericCode: 288,
    withdrawalDate: '2008-01',
  },
  {
    alphabeticCode: 'GHP',
    currency: 'Ghana Cedi',
    entity: 'GHANA',
    minorUnit: '',
    numericCode: 939,
    withdrawalDate: '2007-06',
  },
  {
    alphabeticCode: 'GRD',
    currency: 'Drachma',
    entity: 'GREECE',
    minorUnit: '',
    numericCode: 300,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'GUADELOUPE',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'GNE',
    currency: 'Syli',
    entity: 'GUINEA',
    minorUnit: '',
    numericCode: 324,
    withdrawalDate: '1989-12',
  },
  {
    alphabeticCode: 'GNS',
    currency: 'Syli',
    entity: 'GUINEA',
    minorUnit: '',
    numericCode: 324,
    withdrawalDate: '1986-02',
  },
  {
    alphabeticCode: 'GWE',
    currency: 'Guinea Escudo',
    entity: 'GUINEA-BISSAU',
    minorUnit: '',
    numericCode: 624,
    withdrawalDate: '1978 to 1981',
  },
  {
    alphabeticCode: 'GWP',
    currency: 'Guinea-Bissau Peso',
    entity: 'GUINEA-BISSAU',
    minorUnit: '',
    numericCode: 624,
    withdrawalDate: '1997-05',
  },
  {
    alphabeticCode: 'ITL',
    currency: 'Italian Lira',
    entity: 'HOLY SEE (VATICAN CITY STATE)',
    minorUnit: '',
    numericCode: 380,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'ISJ',
    currency: 'Old Krona',
    entity: 'ICELAND',
    minorUnit: '',
    numericCode: 352,
    withdrawalDate: '1989 to 1990',
  },
  {
    alphabeticCode: 'IEP',
    currency: 'Irish Pound',
    entity: 'IRELAND',
    minorUnit: '',
    numericCode: 372,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'ILP',
    currency: 'Pound',
    entity: 'ISRAEL',
    minorUnit: '',
    numericCode: 376,
    withdrawalDate: '1978 to 1981',
  },
  {
    alphabeticCode: 'ILR',
    currency: 'Old Shekel',
    entity: 'ISRAEL',
    minorUnit: '',
    numericCode: 376,
    withdrawalDate: '1989 to 1990',
  },
  {
    alphabeticCode: 'ITL',
    currency: 'Italian Lira',
    entity: 'ITALY',
    minorUnit: '',
    numericCode: 380,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'RUR',
    currency: 'Russian Ruble',
    entity: 'KAZAKHSTAN',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '1994-05',
  },
  {
    alphabeticCode: 'RUR',
    currency: 'Russian Ruble',
    entity: 'KYRGYZSTAN',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '1993-01',
  },
  {
    alphabeticCode: 'LAJ',
    currency: 'Pathet Lao Kip',
    entity: 'LAO',
    minorUnit: '',
    numericCode: 418,
    withdrawalDate: '1979-12',
  },
  {
    alphabeticCode: 'LVL',
    currency: 'Latvian Lats',
    entity: 'LATVIA',
    minorUnit: '',
    numericCode: 428,
    withdrawalDate: '2014-01',
  },
  {
    alphabeticCode: 'LVR',
    currency: 'Latvian Ruble',
    entity: 'LATVIA',
    minorUnit: '',
    numericCode: 428,
    withdrawalDate: '1994-12',
  },
  {
    alphabeticCode: 'LSM',
    currency: 'Loti',
    entity: 'LESOTHO',
    minorUnit: '',
    numericCode: 426,
    withdrawalDate: '1985-05',
  },
  {
    alphabeticCode: 'ZAL',
    currency: 'Financial Rand',
    entity: 'LESOTHO',
    minorUnit: '',
    numericCode: 991,
    withdrawalDate: '1995-03',
  },
  {
    alphabeticCode: 'LTL',
    currency: 'Lithuanian Litas',
    entity: 'LITHUANIA',
    minorUnit: '',
    numericCode: 440,
    withdrawalDate: '2014-12',
  },
  {
    alphabeticCode: 'LTT',
    currency: 'Talonas',
    entity: 'LITHUANIA',
    minorUnit: '',
    numericCode: 440,
    withdrawalDate: '1993-07',
  },
  {
    alphabeticCode: 'LUC',
    currency: 'Luxembourg Convertible Franc',
    entity: 'LUXEMBOURG',
    minorUnit: '',
    numericCode: 989,
    withdrawalDate: '1990-03',
  },
  {
    alphabeticCode: 'LUF',
    currency: 'Luxembourg Franc',
    entity: 'LUXEMBOURG',
    minorUnit: '',
    numericCode: 442,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'LUL',
    currency: 'Luxembourg Financial Franc',
    entity: 'LUXEMBOURG',
    minorUnit: '',
    numericCode: 988,
    withdrawalDate: '1990-03',
  },
  {
    alphabeticCode: 'MGF',
    currency: 'Malagasy Franc',
    entity: 'MADAGASCAR',
    minorUnit: '',
    numericCode: 450,
    withdrawalDate: '2004-12',
  },
  {
    alphabeticCode: 'MWK',
    currency: 'Kwacha',
    entity: 'MALAWI',
    minorUnit: '',
    numericCode: 454,
    withdrawalDate: '2016-02',
  },
  {
    alphabeticCode: 'MVQ',
    currency: 'Maldive Rupee',
    entity: 'MALDIVES',
    minorUnit: '',
    numericCode: 462,
    withdrawalDate: '1989-12',
  },
  {
    alphabeticCode: 'MLF',
    currency: 'Mali Franc',
    entity: 'MALI',
    minorUnit: '',
    numericCode: 466,
    withdrawalDate: '1984-11',
  },
  {
    alphabeticCode: 'MTL',
    currency: 'Maltese Lira',
    entity: 'MALTA',
    minorUnit: '',
    numericCode: 470,
    withdrawalDate: '2008-01',
  },
  {
    alphabeticCode: 'MTP',
    currency: 'Maltese Pound',
    entity: 'MALTA',
    minorUnit: '',
    numericCode: 470,
    withdrawalDate: '1983-06',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'MARTINIQUE',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'MRO',
    currency: 'Ouguiya',
    entity: 'MAURITANIA',
    minorUnit: '',
    numericCode: 478,
    withdrawalDate: '2017-12',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'MAYOTTE',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'MXP',
    currency: 'Mexican Peso',
    entity: 'MEXICO',
    minorUnit: '',
    numericCode: 484,
    withdrawalDate: '1993-01',
  },
  {
    alphabeticCode: 'RUR',
    currency: 'Russian Ruble',
    entity: 'MOLDOVA, REPUBLIC OF',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '1993-12',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'MONACO',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'MZE',
    currency: 'Mozambique Escudo',
    entity: 'MOZAMBIQUE',
    minorUnit: '',
    numericCode: 508,
    withdrawalDate: '1978 to 1981',
  },
  {
    alphabeticCode: 'MZM',
    currency: 'Mozambique Metical',
    entity: 'MOZAMBIQUE',
    minorUnit: '',
    numericCode: 508,
    withdrawalDate: '2006-06',
  },
  {
    alphabeticCode: 'NLG',
    currency: 'Netherlands Guilder',
    entity: 'NETHERLANDS',
    minorUnit: '',
    numericCode: 528,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'ANG',
    currency: 'Netherlands Antillean Guilder',
    entity: 'NETHERLANDS ANTILLES',
    minorUnit: '',
    numericCode: 532,
    withdrawalDate: '2010-10',
  },
  {
    alphabeticCode: 'NIC',
    currency: 'Cordoba',
    entity: 'NICARAGUA',
    minorUnit: '',
    numericCode: 558,
    withdrawalDate: '1990-10',
  },
  {
    alphabeticCode: 'PEH',
    currency: 'Sol',
    entity: 'PERU',
    minorUnit: '',
    numericCode: 604,
    withdrawalDate: '1989 to 1990',
  },
  {
    alphabeticCode: 'PEI',
    currency: 'Inti',
    entity: 'PERU',
    minorUnit: '',
    numericCode: 604,
    withdrawalDate: '1991-07',
  },
  {
    alphabeticCode: 'PEN',
    currency: 'Nuevo Sol',
    entity: 'PERU',
    minorUnit: '',
    numericCode: 604,
    withdrawalDate: '2015-12',
  },
  {
    alphabeticCode: 'PES',
    currency: 'Sol',
    entity: 'PERU',
    minorUnit: '',
    numericCode: 604,
    withdrawalDate: '1986-02',
  },
  {
    alphabeticCode: 'PLZ',
    currency: 'Zloty',
    entity: 'POLAND',
    minorUnit: '',
    numericCode: 616,
    withdrawalDate: '1997-01',
  },
  {
    alphabeticCode: 'PTE',
    currency: 'Portuguese Escudo',
    entity: 'PORTUGAL',
    minorUnit: '',
    numericCode: 620,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'RÉUNION',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'ROK',
    currency: 'Leu A/52',
    entity: 'ROMANIA',
    minorUnit: '',
    numericCode: 642,
    withdrawalDate: '1989 to 1990',
  },
  {
    alphabeticCode: 'ROL',
    currency: 'Old Leu',
    entity: 'ROMANIA',
    minorUnit: '',
    numericCode: 642,
    withdrawalDate: '2005-06',
  },
  {
    alphabeticCode: 'RON',
    currency: 'New Romanian Leu',
    entity: 'ROMANIA',
    minorUnit: '',
    numericCode: 946,
    withdrawalDate: '2015-06',
  },
  {
    alphabeticCode: 'RUR',
    currency: 'Russian Ruble',
    entity: 'RUSSIAN FEDERATION',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '2004-01',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'SAINT MARTIN',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '1999-01',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'SAINT PIERRE AND MIQUELON',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'FRF',
    currency: 'French Franc',
    entity: 'SAINT-BARTHÉLEMY',
    minorUnit: '',
    numericCode: 250,
    withdrawalDate: '1999-01',
  },
  {
    alphabeticCode: 'ITL',
    currency: 'Italian Lira',
    entity: 'SAN MARINO',
    minorUnit: '',
    numericCode: 380,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'STD',
    currency: 'Dobra',
    entity: 'SAO TOME AND PRINCIPE',
    minorUnit: '',
    numericCode: 678,
    withdrawalDate: '2017-12',
  },
  {
    alphabeticCode: 'CSD',
    currency: 'Serbian Dinar',
    entity: 'SERBIA AND MONTENEGRO',
    minorUnit: '',
    numericCode: 891,
    withdrawalDate: '2006-10',
  },
  {
    alphabeticCode: 'EUR',
    currency: 'Euro',
    entity: 'SERBIA AND MONTENEGRO',
    minorUnit: '',
    numericCode: 978,
    withdrawalDate: '2006-10',
  },
  {
    alphabeticCode: 'SKK',
    currency: 'Slovak Koruna',
    entity: 'SLOVAKIA',
    minorUnit: '',
    numericCode: 703,
    withdrawalDate: '2009-01',
  },
  {
    alphabeticCode: 'SIT',
    currency: 'Tolar',
    entity: 'SLOVENIA',
    minorUnit: '',
    numericCode: 705,
    withdrawalDate: '2007-01',
  },
  {
    alphabeticCode: 'ZAL',
    currency: 'Financial Rand',
    entity: 'SOUTH AFRICA',
    minorUnit: '',
    numericCode: 991,
    withdrawalDate: '1995-03',
  },
  {
    alphabeticCode: 'SDG',
    currency: 'Sudanese Pound',
    entity: 'SOUTH SUDAN',
    minorUnit: '',
    numericCode: 938,
    withdrawalDate: '2012-09',
  },
  {
    alphabeticCode: 'RHD',
    currency: 'Rhodesian Dollar',
    entity: 'SOUTHERN RHODESIA',
    minorUnit: '',
    numericCode: 716,
    withdrawalDate: '1978 to 1981',
  },
  {
    alphabeticCode: 'ESA',
    currency: 'Spanish Peseta',
    entity: 'SPAIN',
    minorUnit: '',
    numericCode: 996,
    withdrawalDate: '1978 to 1981',
  },
  {
    alphabeticCode: 'ESP',
    currency: 'Spanish Peseta',
    entity: 'SPAIN',
    minorUnit: '',
    numericCode: 724,
    withdrawalDate: '2002-03',
  },
  {
    alphabeticCode: 'SDD',
    currency: 'Sudanese Dinar',
    entity: 'SUDAN',
    minorUnit: '',
    numericCode: 736,
    withdrawalDate: '2007-07',
  },
  {
    alphabeticCode: 'SDP',
    currency: 'Sudanese Pound',
    entity: 'SUDAN',
    minorUnit: '',
    numericCode: 736,
    withdrawalDate: '1998-06',
  },
  {
    alphabeticCode: 'SRG',
    currency: 'Surinam Guilder',
    entity: 'SURINAME',
    minorUnit: '',
    numericCode: 740,
    withdrawalDate: '2003-12',
  },
  {
    alphabeticCode: 'SZL',
    currency: 'Lilangeni',
    entity: 'SWAZILAND',
    minorUnit: '',
    numericCode: 748,
    withdrawalDate: '2018-08',
  },
  {
    alphabeticCode: 'CHC',
    currency: 'WIR Franc (for electronic)',
    entity: 'SWITZERLAND',
    minorUnit: '',
    numericCode: 948,
    withdrawalDate: '2004-11',
  },
  {
    alphabeticCode: 'RUR',
    currency: 'Russian Ruble',
    entity: 'TAJIKISTAN',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '1995-05',
  },
  {
    alphabeticCode: 'TJR',
    currency: 'Tajik Ruble',
    entity: 'TAJIKISTAN',
    minorUnit: '',
    numericCode: 762,
    withdrawalDate: '2001-04',
  },
  {
    alphabeticCode: 'IDR',
    currency: 'Rupiah',
    entity: 'TIMOR-LESTE',
    minorUnit: '',
    numericCode: 360,
    withdrawalDate: '2002-07',
  },
  {
    alphabeticCode: 'TPE',
    currency: 'Timor Escudo',
    entity: 'TIMOR-LESTE',
    minorUnit: '',
    numericCode: 626,
    withdrawalDate: '2002-11',
  },
  {
    alphabeticCode: 'TRL',
    currency: 'Old Turkish Lira',
    entity: 'TURKEY',
    minorUnit: '',
    numericCode: 792,
    withdrawalDate: '2005-12',
  },
  {
    alphabeticCode: 'TRY',
    currency: 'New Turkish Lira',
    entity: 'TURKEY',
    minorUnit: '',
    numericCode: 949,
    withdrawalDate: '2009-01',
  },
  {
    alphabeticCode: 'RUR',
    currency: 'Russian Ruble',
    entity: 'TURKMENISTAN',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '1993-10',
  },
  {
    alphabeticCode: 'TMM',
    currency: 'Turkmenistan Manat',
    entity: 'TURKMENISTAN',
    minorUnit: '',
    numericCode: 795,
    withdrawalDate: '2009-01',
  },
  {
    alphabeticCode: 'UGS',
    currency: 'Uganda Shilling',
    entity: 'UGANDA',
    minorUnit: '',
    numericCode: 800,
    withdrawalDate: '1987-05',
  },
  {
    alphabeticCode: 'UGW',
    currency: 'Old Shilling',
    entity: 'UGANDA',
    minorUnit: '',
    numericCode: 800,
    withdrawalDate: '1989 to 1990',
  },
  {
    alphabeticCode: 'UAK',
    currency: 'Karbovanet',
    entity: 'UKRAINE',
    minorUnit: '',
    numericCode: 804,
    withdrawalDate: '1996-09',
  },
  {
    alphabeticCode: 'SUR',
    currency: 'Rouble',
    entity: 'UNION OF SOVIET SOCIALIST REPUBLICS',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '1990-12',
  },
  {
    alphabeticCode: 'USS',
    currency: 'US Dollar (Same day)',
    entity: 'UNITED STATES',
    minorUnit: '',
    numericCode: 998,
    withdrawalDate: '2014-03',
  },
  {
    alphabeticCode: 'UYN',
    currency: 'Old Uruguay Peso',
    entity: 'URUGUAY',
    minorUnit: '',
    numericCode: 858,
    withdrawalDate: '1989-12',
  },
  {
    alphabeticCode: 'UYP',
    currency: 'Uruguayan Peso',
    entity: 'URUGUAY',
    minorUnit: '',
    numericCode: 858,
    withdrawalDate: '1993-03',
  },
  {
    alphabeticCode: 'RUR',
    currency: 'Russian Ruble',
    entity: 'UZBEKISTAN',
    minorUnit: '',
    numericCode: 810,
    withdrawalDate: '1994-07',
  },
  {
    alphabeticCode: 'VEB',
    currency: 'Bolivar',
    entity: 'VENEZUELA',
    minorUnit: '',
    numericCode: 862,
    withdrawalDate: '2008-01',
  },
  {
    alphabeticCode: 'VEF',
    currency: 'Bolivar Fuerte',
    entity: 'VENEZUELA',
    minorUnit: '',
    numericCode: 937,
    withdrawalDate: '2011-12',
  },
  {
    alphabeticCode: 'VEF',
    currency: 'Bolivar',
    entity: 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
    minorUnit: '',
    numericCode: 937,
    withdrawalDate: '2016-02',
  },
  {
    alphabeticCode: 'VEF',
    currency: 'Bolívar',
    entity: 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
    minorUnit: '',
    numericCode: 937,
    withdrawalDate: '2018-08',
  },
  {
    alphabeticCode: 'VNC',
    currency: 'Old Dong',
    entity: 'VIETNAM',
    minorUnit: '',
    numericCode: 704,
    withdrawalDate: '1989-1990',
  },
  {
    alphabeticCode: 'YDD',
    currency: 'Yemeni Dinar',
    entity: 'YEMEN, DEMOCRATIC',
    minorUnit: '',
    numericCode: 720,
    withdrawalDate: '1991-09',
  },
  {
    alphabeticCode: 'YUD',
    currency: 'New Yugoslavian Dinar',
    entity: 'YUGOSLAVIA',
    minorUnit: '',
    numericCode: 890,
    withdrawalDate: '1990-01',
  },
  {
    alphabeticCode: 'YUM',
    currency: 'New Dinar',
    entity: 'YUGOSLAVIA',
    minorUnit: '',
    numericCode: 891,
    withdrawalDate: '2003-07',
  },
  {
    alphabeticCode: 'YUN',
    currency: 'Yugoslavian Dinar',
    entity: 'YUGOSLAVIA',
    minorUnit: '',
    numericCode: 890,
    withdrawalDate: '1995-11',
  },
  {
    alphabeticCode: 'ZRN',
    currency: 'New Zaire',
    entity: 'ZAIRE',
    minorUnit: '',
    numericCode: 180,
    withdrawalDate: '1999-06',
  },
  {
    alphabeticCode: 'ZRZ',
    currency: 'Zaire',
    entity: 'ZAIRE',
    minorUnit: '',
    numericCode: 180,
    withdrawalDate: '1994-02',
  },
  {
    alphabeticCode: 'ZMK',
    currency: 'Zambian Kwacha',
    entity: 'ZAMBIA',
    minorUnit: '',
    numericCode: 894,
    withdrawalDate: '2012-12',
  },
  {
    alphabeticCode: 'ZWC',
    currency: 'Rhodesian Dollar',
    entity: 'ZIMBABWE',
    minorUnit: '',
    numericCode: 716,
    withdrawalDate: '1989-12',
  },
  {
    alphabeticCode: 'ZWD',
    currency: 'Zimbabwe Dollar (old)',
    entity: 'ZIMBABWE',
    minorUnit: '',
    numericCode: 716,
    withdrawalDate: '2006-08',
  },
  {
    alphabeticCode: 'ZWD',
    currency: 'Zimbabwe Dollar',
    entity: 'ZIMBABWE',
    minorUnit: '',
    numericCode: 716,
    withdrawalDate: '2008-08',
  },
  {
    alphabeticCode: 'ZWN',
    currency: 'Zimbabwe Dollar (new)',
    entity: 'ZIMBABWE',
    minorUnit: '',
    numericCode: 942,
    withdrawalDate: '2006-09',
  },
  {
    alphabeticCode: 'ZWR',
    currency: 'Zimbabwe Dollar',
    entity: 'ZIMBABWE',
    minorUnit: '',
    numericCode: 935,
    withdrawalDate: '2009-06',
  },
  {
    alphabeticCode: 'XFO',
    currency: 'Gold-Franc',
    entity: 'ZZ01_Gold-Franc',
    minorUnit: '',
    numericCode: null,
    withdrawalDate: '2006-10',
  },
  {
    alphabeticCode: 'XRE',
    currency: 'RINET Funds Code',
    entity: 'ZZ02_RINET Funds Code',
    minorUnit: '',
    numericCode: null,
    withdrawalDate: '1999-11',
  },
  {
    alphabeticCode: 'XFU',
    currency: 'UIC-Franc',
    entity: 'ZZ05_UIC-Franc',
    minorUnit: '',
    numericCode: null,
    withdrawalDate: '2013-11',
  },
];
