# Workflow that build the project.
name: Build

# Triggered on every branch at every push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # [1] checkout repo.
      - uses: actions/checkout@v2

      # [2] get node.
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'

      # [3] install dependencies.
      - name: Install dependencies
        run: yarn

      # [4] build project.
      - name: Run build
        run: yarn build
