# Workflow that lint and test with typescript the code.
name: ESLint & Typescript

# Triggered on every branch at every push
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # [1] checkout repo.
      - uses: actions/checkout@v2

      # [2] get node.
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # [3] install dependencies.
      - name: Install dependencies
        run: yarn

      # [4] Test project.
      - name: Run tests
        run: yarn test
