# Workflow that lint and test with typescript the code.
name: ESLint & Typescript

# Triggered on every branch at every push
on: [push]

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      # [1] checkout repo.
      - uses: actions/checkout@v2

      # [2] get node.
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"

      # [3] install dependencies.
      - name: Install dependencies
        run: yarn

      # [4] test typescript.
      - name: Run typescript
        run: yarn typescript

  lint:
    runs-on: ubuntu-latest
    steps:
      # [1] checkout repo.
      - uses: actions/checkout@v2

      # [2] get node.
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"

      # [3] install dependencies.
      - name: Install dependencies
        run: yarn

      # [4] test.
      - name: Run eslint
        run: yarn lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      # [1] checkout repo.
      - uses: actions/checkout@v2

      # [2] get node.
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"

      # [3] install dependencies.
      - name: Install dependencies
        run: yarn

      # [4] test.
      - name: Run jest
        run: yarn test
